version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore Databricks Go SDK because its upgrade requires code generation
      - dependency-name: github.com/databricks/databricks-sdk-go
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    # tagging.yml is generated and maintained externally.
    exclude-paths:
      - .github/workflows/tagging.yml
