version: 2

before:
  hooks:
    - go mod download

builds:
- env:
    - CGO_ENABLED=0
  binary: terraform-provider-databricks_{{ .Tag }}
  ldflags:
    # sets client version, not the default main.version
    - '-X github.com/databricks/databricks-terraform/common.version={{ replace .Version "v" "" }}'
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm64

archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ replace .Version "v" "" }}_{{ .Os }}_{{ .Arch }}'
  files:
    - LICENSE*
    - CHANGELOG*
    - NOTICE*

checksum:
  name_template: '{{ .ProjectName }}_{{ replace .Version "v" "" }}_SHA256SUMS'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}"

signs:
  - artifacts: checksum
    args:
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release: {}
