# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - make singlehtmldocs
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  binary: terraform-provider-db
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: 64-bit
    386: 32-bit
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE*
    - CHANGELOG*
    - NOTICE*
    - docs/build/singlehtml/**/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
