// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.
/*
These generated types are for terraform plugin framework to interact with the terraform state conveniently.

These types follow the same structure as the types in go-sdk.
The only difference is that the primitive types are no longer using the go-native types, but with tfsdk types.
Plus the json tags get converted into tfsdk tags.
We use go-native types for lists and maps intentionally for the ease for converting these types into the go-sdk types.
*/

package dataclassification_tf

import (
	"context"
	"reflect"

	pluginfwcommon "github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/common"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/tfschema"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Auto-tagging configuration for a classification tag. When enabled, detected
// columns are automatically tagged with Unity Catalog tags.
type AutoTaggingConfig struct {
	// Whether auto-tagging is enabled or disabled for this classification tag.
	AutoTaggingMode types.String `tfsdk:"auto_tagging_mode"`
	// The Classification Tag (e.g., "class.name", "class.location")
	ClassificationTag types.String `tfsdk:"classification_tag"`
}

func (to *AutoTaggingConfig) SyncFieldsDuringCreateOrUpdate(ctx context.Context, from AutoTaggingConfig) {
}

func (to *AutoTaggingConfig) SyncFieldsDuringRead(ctx context.Context, from AutoTaggingConfig) {
}

func (m AutoTaggingConfig) ApplySchemaCustomizations(attrs map[string]tfschema.AttributeBuilder) map[string]tfschema.AttributeBuilder {
	attrs["auto_tagging_mode"] = attrs["auto_tagging_mode"].SetRequired()
	attrs["classification_tag"] = attrs["classification_tag"].SetRequired()

	return attrs
}

// GetComplexFieldTypes returns a map of the types of elements in complex fields in AutoTaggingConfig.
// Container types (types.Map, types.List, types.Set) and object types (types.Object) do not carry
// the type information of their elements in the Go type system. This function provides a way to
// retrieve the type information of the elements in complex fields at runtime. The values of the map
// are the reflected types of the contained elements. They must be either primitive values from the
// plugin framework type system (types.String{}, types.Bool{}, types.Int64{}, types.Float64{}) or TF
// SDK values.
func (m AutoTaggingConfig) GetComplexFieldTypes(ctx context.Context) map[string]reflect.Type {
	return map[string]reflect.Type{}
}

// TFSDK types cannot implement the ObjectValuable interface directly, as it would otherwise
// interfere with how the plugin framework retrieves and sets values in state. Thus, AutoTaggingConfig
// only implements ToObjectValue() and Type().
func (m AutoTaggingConfig) ToObjectValue(ctx context.Context) basetypes.ObjectValue {
	return types.ObjectValueMust(
		m.Type(ctx).(basetypes.ObjectType).AttrTypes,
		map[string]attr.Value{
			"auto_tagging_mode":  m.AutoTaggingMode,
			"classification_tag": m.ClassificationTag,
		})
}

// Type implements basetypes.ObjectValuable.
func (m AutoTaggingConfig) Type(ctx context.Context) attr.Type {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"auto_tagging_mode":  types.StringType,
			"classification_tag": types.StringType,
		},
	}
}

// Data Classification configuration for a Unity Catalog catalog. This message
// follows the "At Most One Resource" pattern: at most one CatalogConfig exists
// per catalog. - Full CRUD operations are supported: Create enables Data
// Classification, Delete disables it - It has no unique identifier of its own
// and uses its parent catalog's identifier (catalog_name)
type CatalogConfig struct {
	// List of auto-tagging configurations for this catalog. Empty list means no
	// auto-tagging is enabled.
	AutoTagConfigs types.List `tfsdk:"auto_tag_configs"`
	// Schemas to include in the scan. Empty list is not supported as it results
	// in a no-op scan. If `included_schemas` is not set, all schemas are
	// scanned.
	IncludedSchemas types.Object `tfsdk:"included_schemas"`
	// Resource name in the format: catalogs/{catalog_name}/config.
	Name types.String `tfsdk:"name"`
}

func (to *CatalogConfig) SyncFieldsDuringCreateOrUpdate(ctx context.Context, from CatalogConfig) {
	if !from.AutoTagConfigs.IsNull() && !from.AutoTagConfigs.IsUnknown() && to.AutoTagConfigs.IsNull() && len(from.AutoTagConfigs.Elements()) == 0 {
		// The default representation of an empty list for TF autogenerated resources in the resource state is Null.
		// If a user specified a non-Null, empty list for AutoTagConfigs, and the deserialized field value is Null,
		// set the resulting resource state to the empty list to match the planned value.
		to.AutoTagConfigs = from.AutoTagConfigs
	}
	if !from.IncludedSchemas.IsNull() && !from.IncludedSchemas.IsUnknown() {
		if toIncludedSchemas, ok := to.GetIncludedSchemas(ctx); ok {
			if fromIncludedSchemas, ok := from.GetIncludedSchemas(ctx); ok {
				// Recursively sync the fields of IncludedSchemas
				toIncludedSchemas.SyncFieldsDuringCreateOrUpdate(ctx, fromIncludedSchemas)
				to.SetIncludedSchemas(ctx, toIncludedSchemas)
			}
		}
	}
}

func (to *CatalogConfig) SyncFieldsDuringRead(ctx context.Context, from CatalogConfig) {
	if !from.AutoTagConfigs.IsNull() && !from.AutoTagConfigs.IsUnknown() && to.AutoTagConfigs.IsNull() && len(from.AutoTagConfigs.Elements()) == 0 {
		// The default representation of an empty list for TF autogenerated resources in the resource state is Null.
		// If a user specified a non-Null, empty list for AutoTagConfigs, and the deserialized field value is Null,
		// set the resulting resource state to the empty list to match the planned value.
		to.AutoTagConfigs = from.AutoTagConfigs
	}
	if !from.IncludedSchemas.IsNull() && !from.IncludedSchemas.IsUnknown() {
		if toIncludedSchemas, ok := to.GetIncludedSchemas(ctx); ok {
			if fromIncludedSchemas, ok := from.GetIncludedSchemas(ctx); ok {
				toIncludedSchemas.SyncFieldsDuringRead(ctx, fromIncludedSchemas)
				to.SetIncludedSchemas(ctx, toIncludedSchemas)
			}
		}
	}
}

func (m CatalogConfig) ApplySchemaCustomizations(attrs map[string]tfschema.AttributeBuilder) map[string]tfschema.AttributeBuilder {
	attrs["auto_tag_configs"] = attrs["auto_tag_configs"].SetOptional()
	attrs["included_schemas"] = attrs["included_schemas"].SetOptional()
	attrs["name"] = attrs["name"].SetOptional()

	return attrs
}

// GetComplexFieldTypes returns a map of the types of elements in complex fields in CatalogConfig.
// Container types (types.Map, types.List, types.Set) and object types (types.Object) do not carry
// the type information of their elements in the Go type system. This function provides a way to
// retrieve the type information of the elements in complex fields at runtime. The values of the map
// are the reflected types of the contained elements. They must be either primitive values from the
// plugin framework type system (types.String{}, types.Bool{}, types.Int64{}, types.Float64{}) or TF
// SDK values.
func (m CatalogConfig) GetComplexFieldTypes(ctx context.Context) map[string]reflect.Type {
	return map[string]reflect.Type{
		"auto_tag_configs": reflect.TypeOf(AutoTaggingConfig{}),
		"included_schemas": reflect.TypeOf(CatalogConfigSchemaNames{}),
	}
}

// TFSDK types cannot implement the ObjectValuable interface directly, as it would otherwise
// interfere with how the plugin framework retrieves and sets values in state. Thus, CatalogConfig
// only implements ToObjectValue() and Type().
func (m CatalogConfig) ToObjectValue(ctx context.Context) basetypes.ObjectValue {
	return types.ObjectValueMust(
		m.Type(ctx).(basetypes.ObjectType).AttrTypes,
		map[string]attr.Value{
			"auto_tag_configs": m.AutoTagConfigs,
			"included_schemas": m.IncludedSchemas,
			"name":             m.Name,
		})
}

// Type implements basetypes.ObjectValuable.
func (m CatalogConfig) Type(ctx context.Context) attr.Type {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"auto_tag_configs": basetypes.ListType{
				ElemType: AutoTaggingConfig{}.Type(ctx),
			},
			"included_schemas": CatalogConfigSchemaNames{}.Type(ctx),
			"name":             types.StringType,
		},
	}
}

// GetAutoTagConfigs returns the value of the AutoTagConfigs field in CatalogConfig as
// a slice of AutoTaggingConfig values.
// If the field is unknown or null, the boolean return value is false.
func (m *CatalogConfig) GetAutoTagConfigs(ctx context.Context) ([]AutoTaggingConfig, bool) {
	if m.AutoTagConfigs.IsNull() || m.AutoTagConfigs.IsUnknown() {
		return nil, false
	}
	var v []AutoTaggingConfig
	d := m.AutoTagConfigs.ElementsAs(ctx, &v, true)
	if d.HasError() {
		panic(pluginfwcommon.DiagToString(d))
	}
	return v, true
}

// SetAutoTagConfigs sets the value of the AutoTagConfigs field in CatalogConfig.
func (m *CatalogConfig) SetAutoTagConfigs(ctx context.Context, v []AutoTaggingConfig) {
	vs := make([]attr.Value, 0, len(v))
	for _, e := range v {
		vs = append(vs, e.ToObjectValue(ctx))
	}
	t := m.Type(ctx).(basetypes.ObjectType).AttrTypes["auto_tag_configs"]
	t = t.(attr.TypeWithElementType).ElementType()
	m.AutoTagConfigs = types.ListValueMust(t, vs)
}

// GetIncludedSchemas returns the value of the IncludedSchemas field in CatalogConfig as
// a CatalogConfigSchemaNames value.
// If the field is unknown or null, the boolean return value is false.
func (m *CatalogConfig) GetIncludedSchemas(ctx context.Context) (CatalogConfigSchemaNames, bool) {
	var e CatalogConfigSchemaNames
	if m.IncludedSchemas.IsNull() || m.IncludedSchemas.IsUnknown() {
		return e, false
	}
	var v CatalogConfigSchemaNames
	d := m.IncludedSchemas.As(ctx, &v, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})
	if d.HasError() {
		panic(pluginfwcommon.DiagToString(d))
	}
	return v, true
}

// SetIncludedSchemas sets the value of the IncludedSchemas field in CatalogConfig.
func (m *CatalogConfig) SetIncludedSchemas(ctx context.Context, v CatalogConfigSchemaNames) {
	vs := v.ToObjectValue(ctx)
	m.IncludedSchemas = vs
}

// Wrapper message for a list of schema names.
type CatalogConfigSchemaNames struct {
	Names types.List `tfsdk:"names"`
}

func (to *CatalogConfigSchemaNames) SyncFieldsDuringCreateOrUpdate(ctx context.Context, from CatalogConfigSchemaNames) {
}

func (to *CatalogConfigSchemaNames) SyncFieldsDuringRead(ctx context.Context, from CatalogConfigSchemaNames) {
}

func (m CatalogConfigSchemaNames) ApplySchemaCustomizations(attrs map[string]tfschema.AttributeBuilder) map[string]tfschema.AttributeBuilder {
	attrs["names"] = attrs["names"].SetRequired()

	return attrs
}

// GetComplexFieldTypes returns a map of the types of elements in complex fields in CatalogConfigSchemaNames.
// Container types (types.Map, types.List, types.Set) and object types (types.Object) do not carry
// the type information of their elements in the Go type system. This function provides a way to
// retrieve the type information of the elements in complex fields at runtime. The values of the map
// are the reflected types of the contained elements. They must be either primitive values from the
// plugin framework type system (types.String{}, types.Bool{}, types.Int64{}, types.Float64{}) or TF
// SDK values.
func (m CatalogConfigSchemaNames) GetComplexFieldTypes(ctx context.Context) map[string]reflect.Type {
	return map[string]reflect.Type{
		"names": reflect.TypeOf(types.String{}),
	}
}

// TFSDK types cannot implement the ObjectValuable interface directly, as it would otherwise
// interfere with how the plugin framework retrieves and sets values in state. Thus, CatalogConfigSchemaNames
// only implements ToObjectValue() and Type().
func (m CatalogConfigSchemaNames) ToObjectValue(ctx context.Context) basetypes.ObjectValue {
	return types.ObjectValueMust(
		m.Type(ctx).(basetypes.ObjectType).AttrTypes,
		map[string]attr.Value{
			"names": m.Names,
		})
}

// Type implements basetypes.ObjectValuable.
func (m CatalogConfigSchemaNames) Type(ctx context.Context) attr.Type {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"names": basetypes.ListType{
				ElemType: types.StringType,
			},
		},
	}
}

// GetNames returns the value of the Names field in CatalogConfigSchemaNames as
// a slice of types.String values.
// If the field is unknown or null, the boolean return value is false.
func (m *CatalogConfigSchemaNames) GetNames(ctx context.Context) ([]types.String, bool) {
	if m.Names.IsNull() || m.Names.IsUnknown() {
		return nil, false
	}
	var v []types.String
	d := m.Names.ElementsAs(ctx, &v, true)
	if d.HasError() {
		panic(pluginfwcommon.DiagToString(d))
	}
	return v, true
}

// SetNames sets the value of the Names field in CatalogConfigSchemaNames.
func (m *CatalogConfigSchemaNames) SetNames(ctx context.Context, v []types.String) {
	vs := make([]attr.Value, 0, len(v))
	for _, e := range v {
		vs = append(vs, e)
	}
	t := m.Type(ctx).(basetypes.ObjectType).AttrTypes["names"]
	t = t.(attr.TypeWithElementType).ElementType()
	m.Names = types.ListValueMust(t, vs)
}

type CreateCatalogConfigRequest struct {
	// The configuration to create.
	CatalogConfig types.Object `tfsdk:"catalog_config"`
	// Parent resource in the format: catalogs/{catalog_name}
	Parent types.String `tfsdk:"-"`
}

func (to *CreateCatalogConfigRequest) SyncFieldsDuringCreateOrUpdate(ctx context.Context, from CreateCatalogConfigRequest) {
	if !from.CatalogConfig.IsNull() && !from.CatalogConfig.IsUnknown() {
		if toCatalogConfig, ok := to.GetCatalogConfig(ctx); ok {
			if fromCatalogConfig, ok := from.GetCatalogConfig(ctx); ok {
				// Recursively sync the fields of CatalogConfig
				toCatalogConfig.SyncFieldsDuringCreateOrUpdate(ctx, fromCatalogConfig)
				to.SetCatalogConfig(ctx, toCatalogConfig)
			}
		}
	}
}

func (to *CreateCatalogConfigRequest) SyncFieldsDuringRead(ctx context.Context, from CreateCatalogConfigRequest) {
	if !from.CatalogConfig.IsNull() && !from.CatalogConfig.IsUnknown() {
		if toCatalogConfig, ok := to.GetCatalogConfig(ctx); ok {
			if fromCatalogConfig, ok := from.GetCatalogConfig(ctx); ok {
				toCatalogConfig.SyncFieldsDuringRead(ctx, fromCatalogConfig)
				to.SetCatalogConfig(ctx, toCatalogConfig)
			}
		}
	}
}

func (m CreateCatalogConfigRequest) ApplySchemaCustomizations(attrs map[string]tfschema.AttributeBuilder) map[string]tfschema.AttributeBuilder {
	attrs["catalog_config"] = attrs["catalog_config"].SetRequired()
	attrs["parent"] = attrs["parent"].SetRequired()

	return attrs
}

// GetComplexFieldTypes returns a map of the types of elements in complex fields in CreateCatalogConfigRequest.
// Container types (types.Map, types.List, types.Set) and object types (types.Object) do not carry
// the type information of their elements in the Go type system. This function provides a way to
// retrieve the type information of the elements in complex fields at runtime. The values of the map
// are the reflected types of the contained elements. They must be either primitive values from the
// plugin framework type system (types.String{}, types.Bool{}, types.Int64{}, types.Float64{}) or TF
// SDK values.
func (m CreateCatalogConfigRequest) GetComplexFieldTypes(ctx context.Context) map[string]reflect.Type {
	return map[string]reflect.Type{
		"catalog_config": reflect.TypeOf(CatalogConfig{}),
	}
}

// TFSDK types cannot implement the ObjectValuable interface directly, as it would otherwise
// interfere with how the plugin framework retrieves and sets values in state. Thus, CreateCatalogConfigRequest
// only implements ToObjectValue() and Type().
func (m CreateCatalogConfigRequest) ToObjectValue(ctx context.Context) basetypes.ObjectValue {
	return types.ObjectValueMust(
		m.Type(ctx).(basetypes.ObjectType).AttrTypes,
		map[string]attr.Value{
			"catalog_config": m.CatalogConfig,
			"parent":         m.Parent,
		})
}

// Type implements basetypes.ObjectValuable.
func (m CreateCatalogConfigRequest) Type(ctx context.Context) attr.Type {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"catalog_config": CatalogConfig{}.Type(ctx),
			"parent":         types.StringType,
		},
	}
}

// GetCatalogConfig returns the value of the CatalogConfig field in CreateCatalogConfigRequest as
// a CatalogConfig value.
// If the field is unknown or null, the boolean return value is false.
func (m *CreateCatalogConfigRequest) GetCatalogConfig(ctx context.Context) (CatalogConfig, bool) {
	var e CatalogConfig
	if m.CatalogConfig.IsNull() || m.CatalogConfig.IsUnknown() {
		return e, false
	}
	var v CatalogConfig
	d := m.CatalogConfig.As(ctx, &v, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})
	if d.HasError() {
		panic(pluginfwcommon.DiagToString(d))
	}
	return v, true
}

// SetCatalogConfig sets the value of the CatalogConfig field in CreateCatalogConfigRequest.
func (m *CreateCatalogConfigRequest) SetCatalogConfig(ctx context.Context, v CatalogConfig) {
	vs := v.ToObjectValue(ctx)
	m.CatalogConfig = vs
}

type DeleteCatalogConfigRequest struct {
	// Resource name in the format: catalogs/{catalog_name}/config
	Name types.String `tfsdk:"-"`
}

func (to *DeleteCatalogConfigRequest) SyncFieldsDuringCreateOrUpdate(ctx context.Context, from DeleteCatalogConfigRequest) {
}

func (to *DeleteCatalogConfigRequest) SyncFieldsDuringRead(ctx context.Context, from DeleteCatalogConfigRequest) {
}

func (m DeleteCatalogConfigRequest) ApplySchemaCustomizations(attrs map[string]tfschema.AttributeBuilder) map[string]tfschema.AttributeBuilder {
	attrs["name"] = attrs["name"].SetRequired()

	return attrs
}

// GetComplexFieldTypes returns a map of the types of elements in complex fields in DeleteCatalogConfigRequest.
// Container types (types.Map, types.List, types.Set) and object types (types.Object) do not carry
// the type information of their elements in the Go type system. This function provides a way to
// retrieve the type information of the elements in complex fields at runtime. The values of the map
// are the reflected types of the contained elements. They must be either primitive values from the
// plugin framework type system (types.String{}, types.Bool{}, types.Int64{}, types.Float64{}) or TF
// SDK values.
func (m DeleteCatalogConfigRequest) GetComplexFieldTypes(ctx context.Context) map[string]reflect.Type {
	return map[string]reflect.Type{}
}

// TFSDK types cannot implement the ObjectValuable interface directly, as it would otherwise
// interfere with how the plugin framework retrieves and sets values in state. Thus, DeleteCatalogConfigRequest
// only implements ToObjectValue() and Type().
func (m DeleteCatalogConfigRequest) ToObjectValue(ctx context.Context) basetypes.ObjectValue {
	return types.ObjectValueMust(
		m.Type(ctx).(basetypes.ObjectType).AttrTypes,
		map[string]attr.Value{
			"name": m.Name,
		})
}

// Type implements basetypes.ObjectValuable.
func (m DeleteCatalogConfigRequest) Type(ctx context.Context) attr.Type {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"name": types.StringType,
		},
	}
}

type GetCatalogConfigRequest struct {
	// Resource name in the format: catalogs/{catalog_name}/config
	Name types.String `tfsdk:"-"`
}

func (to *GetCatalogConfigRequest) SyncFieldsDuringCreateOrUpdate(ctx context.Context, from GetCatalogConfigRequest) {
}

func (to *GetCatalogConfigRequest) SyncFieldsDuringRead(ctx context.Context, from GetCatalogConfigRequest) {
}

func (m GetCatalogConfigRequest) ApplySchemaCustomizations(attrs map[string]tfschema.AttributeBuilder) map[string]tfschema.AttributeBuilder {
	attrs["name"] = attrs["name"].SetRequired()

	return attrs
}

// GetComplexFieldTypes returns a map of the types of elements in complex fields in GetCatalogConfigRequest.
// Container types (types.Map, types.List, types.Set) and object types (types.Object) do not carry
// the type information of their elements in the Go type system. This function provides a way to
// retrieve the type information of the elements in complex fields at runtime. The values of the map
// are the reflected types of the contained elements. They must be either primitive values from the
// plugin framework type system (types.String{}, types.Bool{}, types.Int64{}, types.Float64{}) or TF
// SDK values.
func (m GetCatalogConfigRequest) GetComplexFieldTypes(ctx context.Context) map[string]reflect.Type {
	return map[string]reflect.Type{}
}

// TFSDK types cannot implement the ObjectValuable interface directly, as it would otherwise
// interfere with how the plugin framework retrieves and sets values in state. Thus, GetCatalogConfigRequest
// only implements ToObjectValue() and Type().
func (m GetCatalogConfigRequest) ToObjectValue(ctx context.Context) basetypes.ObjectValue {
	return types.ObjectValueMust(
		m.Type(ctx).(basetypes.ObjectType).AttrTypes,
		map[string]attr.Value{
			"name": m.Name,
		})
}

// Type implements basetypes.ObjectValuable.
func (m GetCatalogConfigRequest) Type(ctx context.Context) attr.Type {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"name": types.StringType,
		},
	}
}

type UpdateCatalogConfigRequest struct {
	// The configuration to apply to the catalog. The name field in
	// catalog_config identifies which resource to update.
	CatalogConfig types.Object `tfsdk:"catalog_config"`
	// Resource name in the format: catalogs/{catalog_name}/config.
	Name types.String `tfsdk:"-"`
	// Field mask specifying which fields to update.
	UpdateMask types.String `tfsdk:"-"`
}

func (to *UpdateCatalogConfigRequest) SyncFieldsDuringCreateOrUpdate(ctx context.Context, from UpdateCatalogConfigRequest) {
	if !from.CatalogConfig.IsNull() && !from.CatalogConfig.IsUnknown() {
		if toCatalogConfig, ok := to.GetCatalogConfig(ctx); ok {
			if fromCatalogConfig, ok := from.GetCatalogConfig(ctx); ok {
				// Recursively sync the fields of CatalogConfig
				toCatalogConfig.SyncFieldsDuringCreateOrUpdate(ctx, fromCatalogConfig)
				to.SetCatalogConfig(ctx, toCatalogConfig)
			}
		}
	}
}

func (to *UpdateCatalogConfigRequest) SyncFieldsDuringRead(ctx context.Context, from UpdateCatalogConfigRequest) {
	if !from.CatalogConfig.IsNull() && !from.CatalogConfig.IsUnknown() {
		if toCatalogConfig, ok := to.GetCatalogConfig(ctx); ok {
			if fromCatalogConfig, ok := from.GetCatalogConfig(ctx); ok {
				toCatalogConfig.SyncFieldsDuringRead(ctx, fromCatalogConfig)
				to.SetCatalogConfig(ctx, toCatalogConfig)
			}
		}
	}
}

func (m UpdateCatalogConfigRequest) ApplySchemaCustomizations(attrs map[string]tfschema.AttributeBuilder) map[string]tfschema.AttributeBuilder {
	attrs["catalog_config"] = attrs["catalog_config"].SetRequired()
	attrs["name"] = attrs["name"].SetRequired()
	attrs["update_mask"] = attrs["update_mask"].SetRequired()

	return attrs
}

// GetComplexFieldTypes returns a map of the types of elements in complex fields in UpdateCatalogConfigRequest.
// Container types (types.Map, types.List, types.Set) and object types (types.Object) do not carry
// the type information of their elements in the Go type system. This function provides a way to
// retrieve the type information of the elements in complex fields at runtime. The values of the map
// are the reflected types of the contained elements. They must be either primitive values from the
// plugin framework type system (types.String{}, types.Bool{}, types.Int64{}, types.Float64{}) or TF
// SDK values.
func (m UpdateCatalogConfigRequest) GetComplexFieldTypes(ctx context.Context) map[string]reflect.Type {
	return map[string]reflect.Type{
		"catalog_config": reflect.TypeOf(CatalogConfig{}),
	}
}

// TFSDK types cannot implement the ObjectValuable interface directly, as it would otherwise
// interfere with how the plugin framework retrieves and sets values in state. Thus, UpdateCatalogConfigRequest
// only implements ToObjectValue() and Type().
func (m UpdateCatalogConfigRequest) ToObjectValue(ctx context.Context) basetypes.ObjectValue {
	return types.ObjectValueMust(
		m.Type(ctx).(basetypes.ObjectType).AttrTypes,
		map[string]attr.Value{
			"catalog_config": m.CatalogConfig,
			"name":           m.Name,
			"update_mask":    m.UpdateMask,
		})
}

// Type implements basetypes.ObjectValuable.
func (m UpdateCatalogConfigRequest) Type(ctx context.Context) attr.Type {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"catalog_config": CatalogConfig{}.Type(ctx),
			"name":           types.StringType,
			"update_mask":    types.StringType,
		},
	}
}

// GetCatalogConfig returns the value of the CatalogConfig field in UpdateCatalogConfigRequest as
// a CatalogConfig value.
// If the field is unknown or null, the boolean return value is false.
func (m *UpdateCatalogConfigRequest) GetCatalogConfig(ctx context.Context) (CatalogConfig, bool) {
	var e CatalogConfig
	if m.CatalogConfig.IsNull() || m.CatalogConfig.IsUnknown() {
		return e, false
	}
	var v CatalogConfig
	d := m.CatalogConfig.As(ctx, &v, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})
	if d.HasError() {
		panic(pluginfwcommon.DiagToString(d))
	}
	return v, true
}

// SetCatalogConfig sets the value of the CatalogConfig field in UpdateCatalogConfigRequest.
func (m *UpdateCatalogConfigRequest) SetCatalogConfig(ctx context.Context, v CatalogConfig) {
	vs := v.ToObjectValue(ctx)
	m.CatalogConfig = vs
}
