// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.
package tfschema

import (
	"context"
	"fmt"
	"reflect"
	"regexp"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Namespace is used to store the namespace for unified terraform provider
// across resources and data sources onboarded to plugin framework.
// Resources and data sources will use the underlying ProviderConfig and ProviderConfigData
// type respectively to store the provider configurations.
// This needs to be kept in sync with Namespace for resources and data sources on SDKv2
// defined in common/unified_provider.go and for autogenerated resources.
type Namespace struct {
	ProviderConfig types.Object `tfsdk:"provider_config"`
}

// Namespace_SdkV2 is used to store the namespace for unified terraform provider
// across resources and data sources onboarded to plugin framework and are SDKv2 compatible.
// This needs to be kept in sync with Namespace defined above.
type Namespace_SdkV2 struct {
	ProviderConfig types.List `tfsdk:"provider_config"`
}

// ProviderConfig is used to store the provider configurations for unified terraform provider
// across resources onboarded to plugin framework.
// When adding new fields, update ToObjectValue, Type, and all functions that
// construct or inspect ProviderConfig (e.g. PopulateProviderConfigInState,
// WorkspaceDriftDetection, ValidateWorkspaceID).
type ProviderConfig struct {
	WorkspaceID types.String `tfsdk:"workspace_id"`
}

// ApplySchemaCustomizations applies the schema customizations to the ProviderConfig type.
func (r ProviderConfig) ApplySchemaCustomizations(attrs map[string]AttributeBuilder) map[string]AttributeBuilder {
	attrs["workspace_id"] = attrs["workspace_id"].SetRequired()
	attrs["workspace_id"] = attrs["workspace_id"].(StringAttributeBuilder).AddPlanModifier(
		stringplanmodifier.RequiresReplaceIf(workspaceIDPlanModifier, "", ""))
	attrs["workspace_id"] = attrs["workspace_id"].(StringAttributeBuilder).AddValidator(stringvalidator.LengthAtLeast(1))
	attrs["workspace_id"] = attrs["workspace_id"].(StringAttributeBuilder).AddValidator(
		stringvalidator.RegexMatches(regexp.MustCompile(`^\d+$`), "workspace_id must be a valid integer"))
	return attrs
}

// workspaceIDPlanModifier is a plan modifier that requires replacement if the
// workspace_id changes from one non-empty value to another
func workspaceIDPlanModifier(ctx context.Context, req planmodifier.StringRequest, resp *stringplanmodifier.RequiresReplaceIfFuncResponse) {
	// Require replacement if workspace_id changes from one non-empty value to another
	oldValue := req.StateValue.ValueString()
	newValue := req.PlanValue.ValueString()

	if oldValue != "" && newValue != "" && oldValue != newValue {
		resp.RequiresReplace = true
	}
}

// GetComplexFieldTypes returns a map of the types of elements in complex fields in ProviderConfig.
func (r ProviderConfig) GetComplexFieldTypes(ctx context.Context) map[string]reflect.Type {
	return map[string]reflect.Type{}
}

// ToObjectValue returns the object value for the resource
func (r ProviderConfig) ToObjectValue(ctx context.Context) basetypes.ObjectValue {
	return types.ObjectValueMust(
		r.Type(ctx).(basetypes.ObjectType).AttrTypes,
		map[string]attr.Value{
			"workspace_id": r.WorkspaceID,
		},
	)
}

// Type returns the object type for the ProviderConfig type.
func (r ProviderConfig) Type(ctx context.Context) attr.Type {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"workspace_id": types.StringType,
		},
	}
}

// ProviderConfigData is used to store the provider configurations for unified terraform provider
// across data sources onboarded to plugin framework.
type ProviderConfigData struct {
	WorkspaceID types.String `tfsdk:"workspace_id"`
}

// ApplySchemaCustomizations applies the schema customizations to the ProviderConfigData type.
func (r ProviderConfigData) ApplySchemaCustomizations(attrs map[string]AttributeBuilder) map[string]AttributeBuilder {
	attrs["workspace_id"] = attrs["workspace_id"].SetOptional()
	attrs["workspace_id"] = attrs["workspace_id"].SetComputed()
	attrs["workspace_id"] = attrs["workspace_id"].(StringAttributeBuilder).AddValidator(stringvalidator.LengthAtLeast(1))
	attrs["workspace_id"] = attrs["workspace_id"].(StringAttributeBuilder).AddValidator(
		stringvalidator.RegexMatches(regexp.MustCompile(`^\d+$`), "workspace_id must be a valid integer"))
	return attrs
}

// GetComplexFieldTypes returns a map of the types of elements in complex fields in ProviderConfigData.
func (r ProviderConfigData) GetComplexFieldTypes(ctx context.Context) map[string]reflect.Type {
	return map[string]reflect.Type{}
}

// ToObjectValue returns the object value for the data source
func (r ProviderConfigData) ToObjectValue(ctx context.Context) basetypes.ObjectValue {
	return types.ObjectValueMust(
		r.Type(ctx).(basetypes.ObjectType).AttrTypes,
		map[string]attr.Value{
			"workspace_id": r.WorkspaceID,
		},
	)
}

// Type returns the object type for the ProviderConfigData type.
func (r ProviderConfigData) Type(ctx context.Context) attr.Type {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"workspace_id": types.StringType,
		},
	}
}

// GetWorkspaceID_SdkV2 extracts the workspace ID from a provider_config list (for SdkV2-compatible resources).
// It returns the workspace ID string and any diagnostics encountered during extraction.
// If the provider_config is not set, it returns an empty string with no diagnostics.
func GetWorkspaceID_SdkV2(ctx context.Context, providerConfig types.List) (string, diag.Diagnostics) {
	var diags diag.Diagnostics
	var workspaceID string

	if providerConfig.IsNull() || providerConfig.IsUnknown() {
		return workspaceID, diags
	}

	var namespaceList []ProviderConfig
	diags.Append(providerConfig.ElementsAs(ctx, &namespaceList, true)...)
	if diags.HasError() {
		return workspaceID, diags
	}

	if len(namespaceList) > 0 {
		workspaceID = namespaceList[0].WorkspaceID.ValueString()
	}

	return workspaceID, diags
}

// GetWorkspaceIDResource extracts the workspace ID from a provider_config object (for resources).
// It returns the workspace ID string and any diagnostics encountered during extraction.
// If the provider_config is not set, it returns an empty string with no diagnostics.
func GetWorkspaceIDResource(ctx context.Context, providerConfig types.Object) (string, diag.Diagnostics) {
	var diags diag.Diagnostics
	var workspaceID string

	if providerConfig.IsNull() || providerConfig.IsUnknown() {
		return workspaceID, diags
	}

	var namespace ProviderConfig
	diags.Append(providerConfig.As(ctx, &namespace, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)
	if diags.HasError() {
		return workspaceID, diags
	}

	workspaceID = namespace.WorkspaceID.ValueString()

	return workspaceID, diags
}

// GetWorkspaceIDDataSource extracts the workspace ID from a provider_config object (for data sources).
// It returns the workspace ID string and any diagnostics encountered during extraction.
// If the provider_config is not set, it returns an empty string with no diagnostics.
func GetWorkspaceIDDataSource(ctx context.Context, providerConfig types.Object) (string, diag.Diagnostics) {
	var diags diag.Diagnostics
	var workspaceID string

	if providerConfig.IsNull() || providerConfig.IsUnknown() {
		return workspaceID, diags
	}

	var namespace ProviderConfigData
	diags.Append(providerConfig.As(ctx, &namespace, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)
	if diags.HasError() {
		return workspaceID, diags
	}

	workspaceID = namespace.WorkspaceID.ValueString()

	return workspaceID, diags
}

// ProviderConfigPlanModifier handles provider_config during plan:
//   - On Create (no prior state): if config doesn't set provider_config, sets plan
//     to unknown so the provider can populate it during apply.
//   - On Update: copies prior state to plan (like UseStateForUnknown) to avoid
//     perpetual diffs when provider_config is absent from config.
type ProviderConfigPlanModifier struct{}

func (m ProviderConfigPlanModifier) Description(ctx context.Context) string {
	return "Handles provider_config for create and update lifecycle."
}

func (m ProviderConfigPlanModifier) MarkdownDescription(ctx context.Context) string {
	return m.Description(ctx)
}

func (m ProviderConfigPlanModifier) PlanModifyObject(ctx context.Context, req planmodifier.ObjectRequest, resp *planmodifier.ObjectResponse) {
	// If config has a value, let it through (user explicitly set provider_config).
	if !req.ConfigValue.IsNull() && !req.ConfigValue.IsUnknown() {
		return
	}
	// Config is null (user didn't set provider_config).
	if req.StateValue.IsNull() || req.State.Raw.IsNull() {
		// Create: no prior state. Set plan to unknown so TC allows
		// the provider to populate it during apply.
		resp.PlanValue = types.ObjectUnknown(ProviderConfig{}.Type(ctx).(types.ObjectType).AttrTypes)
	} else {
		// Update: copy prior state to plan (like UseStateForUnknown).
		resp.PlanValue = req.StateValue
	}
}

// UnifiedProviderClient is the subset of common.DatabricksClient needed by
// the shared workspace_id helpers. Both the real provider client and the
// synthetic test client satisfy this interface.
type UnifiedProviderClient interface {
	// GetProviderWorkspaceID returns the provider-level workspace_id from Config.
	GetProviderWorkspaceID() string
	// CurrentWorkspaceID resolves the workspace ID from the provider's host.
	CurrentWorkspaceID(ctx context.Context) (int64, error)
	// ValidateWorkspaceAccess validates that the workspace client for the given
	// workspace_id is reachable. Returns diagnostics on failure.
	ValidateWorkspaceAccess(ctx context.Context, workspaceID string) diag.Diagnostics
}

// WorkspaceDriftDetection compares the old (state) and new (config/provider)
// effective workspace IDs and triggers RequiresReplace when they differ.
// Only runs for updates — during create there is no prior state to compare.
func WorkspaceDriftDetection(ctx context.Context, client UnifiedProviderClient, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	// No prior state means create — nothing to compare.
	if req.State.Raw.IsNull() {
		return
	}

	// Get old effective workspace ID from state.
	var statePC types.Object
	resp.Diagnostics.Append(req.State.GetAttribute(ctx, path.Root("provider_config"), &statePC)...)
	if resp.Diagnostics.HasError() {
		return
	}
	oldWsID, diags := GetWorkspaceIDResource(ctx, statePC)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if oldWsID == "" {
		oldWsID = client.GetProviderWorkspaceID()
	}

	// Get new effective workspace ID from config (the raw user config, NOT
	// the plan which may contain the preserved state value).
	var cfgPC types.Object
	resp.Diagnostics.Append(req.Config.GetAttribute(ctx, path.Root("provider_config"), &cfgPC)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var newWsID string
	if !cfgPC.IsNull() && !cfgPC.IsUnknown() {
		var wsIDDiags diag.Diagnostics
		newWsID, wsIDDiags = GetWorkspaceIDResource(ctx, cfgPC)
		resp.Diagnostics.Append(wsIDDiags...)
		if resp.Diagnostics.HasError() {
			return
		}
	}
	if newWsID == "" {
		newWsID = client.GetProviderWorkspaceID()
	}
	// Fallback to cached workspace ID for workspace-level providers.
	if newWsID == "" {
		if cachedID, err := client.CurrentWorkspaceID(ctx); err == nil && cachedID != 0 {
			newWsID = strconv.FormatInt(cachedID, 10)
		}
	}

	if oldWsID != "" && newWsID == "" {
		resp.Diagnostics.AddError("Missing workspace_id",
			fmt.Sprintf("resource has provider_config.workspace_id = %s in state but no workspace_id is configured. "+
				"Set workspace_id in the provider configuration or in the resource's provider_config block", oldWsID))
		return
	}

	if oldWsID != "" && newWsID != "" && oldWsID != newWsID {
		resp.RequiresReplace = append(resp.RequiresReplace,
			path.Root("provider_config").AtName("workspace_id"))
		resp.Diagnostics.Append(resp.Plan.SetAttribute(ctx, path.Root("provider_config"),
			ProviderConfig{WorkspaceID: types.StringValue(newWsID)}.ToObjectValue(ctx))...)
	}
}

// ValidateWorkspaceID validates that the workspace client for the planned
// workspace_id is reachable. Runs for both create and update.
// Call this from any PF resource's ModifyPlan that has a provider_config block.
func ValidateWorkspaceID(ctx context.Context, client UnifiedProviderClient, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	var planPC types.Object
	// Read from resp.Plan (not req.Plan) because WorkspaceDriftDetection may
	// have updated provider_config in the plan to reflect a new workspace_id.
	resp.Diagnostics.Append(resp.Plan.GetAttribute(ctx, path.Root("provider_config"), &planPC)...)
	if resp.Diagnostics.HasError() {
		return
	}
	workspaceID, diags := GetWorkspaceIDResource(ctx, planPC)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if workspaceID == "" {
		workspaceID = client.GetProviderWorkspaceID()
	}
	resp.Diagnostics.Append(client.ValidateWorkspaceAccess(ctx, workspaceID)...)
}

// PopulateProviderConfigInState resolves the effective workspace ID and sets it
// in the response state. Call this at the end of every Read method for
// unified-provider Plugin Framework resources.
//
// During refresh reads (terraform plan), providerConfig comes from the prior
// state (req.State). If it already contains a workspace ID, that value is
// preserved — the fallback to workspace_id / host is only used on the
// first time (after Create/Import) when no workspace ID is in state yet.
// Preserving the prior state value is critical: ModifyPlan compares the old
// effective workspace ID against the new one to trigger ForceNew when they
// differ. Overwriting it here would make that detection impossible.
func PopulateProviderConfigInState(ctx context.Context, client UnifiedProviderClient,
	providerConfig types.Object, state *tfsdk.State) diag.Diagnostics {
	// GetWorkspaceIDResource reads from providerConfig, which during Read
	// comes from the prior state. If the state already has a workspace ID,
	// it is returned here and the fallbacks below are skipped — preserving
	// the old value for ModifyPlan.
	wsID, diags := GetWorkspaceIDResource(ctx, providerConfig)
	if diags.HasError() {
		return diags
	}
	if wsID == "" {
		wsID = client.GetProviderWorkspaceID()
	}
	if wsID == "" {
		id, err := client.CurrentWorkspaceID(ctx)
		if err != nil {
			return diag.Diagnostics{diag.NewErrorDiagnostic(
				"failed to resolve workspace ID for provider_config state population", err.Error())}
		}
		wsID = strconv.FormatInt(id, 10)
	}
	if wsID != "" {
		diags.Append(state.SetAttribute(ctx, path.Root("provider_config"),
			ProviderConfig{WorkspaceID: types.StringValue(wsID)}.ToObjectValue(ctx))...)
	}
	return diags
}

// PopulateProviderConfigInStateForDataSource resolves the effective workspace ID
// and sets it in the response state. Call this at the end of every Read method
// for unified-provider Plugin Framework data sources.
//
// Unlike PopulateProviderConfigInState (for resources), data sources re-read
// every time so there is no "preserve existing" logic.
func PopulateProviderConfigInStateForDataSource(ctx context.Context, client UnifiedProviderClient,
	providerConfig types.Object, state *tfsdk.State) diag.Diagnostics {
	wsID, diags := GetWorkspaceIDDataSource(ctx, providerConfig)
	if diags.HasError() {
		return diags
	}
	if wsID == "" {
		wsID = client.GetProviderWorkspaceID()
	}
	if wsID == "" {
		id, err := client.CurrentWorkspaceID(ctx)
		if err != nil {
			return diag.Diagnostics{diag.NewErrorDiagnostic(
				"failed to resolve workspace ID for provider_config state population", err.Error())}
		}
		wsID = strconv.FormatInt(id, 10)
	}
	if wsID != "" {
		diags.Append(state.SetAttribute(ctx, path.Root("provider_config"),
			ProviderConfigData{WorkspaceID: types.StringValue(wsID)}.ToObjectValue(ctx))...)
	}
	return diags
}
