// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package disaster_recovery_stable_url

import (
	"context"
	"fmt"
	"reflect"
	"strings"

	"github.com/databricks/databricks-sdk-go/apierr"
	"github.com/databricks/databricks-sdk-go/service/disasterrecovery"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/autogen"
	pluginfwcontext "github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/context"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/converters"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/declarative"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/tfschema"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

const resourceName = "disaster_recovery_stable_url"

var _ resource.ResourceWithConfigure = &StableUrlResource{}

func ResourceStableUrl() resource.Resource {
	return &StableUrlResource{}
}

type StableUrlResource struct {
	Client *autogen.DatabricksClient
}

// StableUrl extends the main model with additional fields.
type StableUrl struct {
	// The workspace this stable URL is initially bound to. Used only in Create
	// requests to associate the stable URL with a workspace. Not returned in
	// responses. Mirrors FailoverGroup.initial_primary_region semantics.
	InitialWorkspaceId types.String `tfsdk:"initial_workspace_id"`
	// Fully qualified resource name. Format:
	// accounts/{account_id}/stable-urls/{stable_url_id}.
	Name types.String `tfsdk:"name"`
	// The parent resource. Format: accounts/{account_id}.
	Parent types.String `tfsdk:"parent"`
	// Client-provided identifier for the stable URL. Used to construct the
	// resource name as {parent}/stable-urls/{stable_url_id}.
	StableUrlId types.String `tfsdk:"stable_url_id"`
	// The stable URL endpoint. Generated by the backend on creation and
	// immutable thereafter. For non-Private-Link workspaces this is
	// `https://<spog_host>/?c=<connection_id>`. For Private-Link workspaces
	// this is the per-connection hostname.
	Url types.String `tfsdk:"url"`
}

// GetComplexFieldTypes returns a map of the types of elements in complex fields in the extended
// StableUrl struct. Container types (types.Map, types.List, types.Set) and
// object types (types.Object) do not carry the type information of their elements in the Go
// type system. This function provides a way to retrieve the type information of the elements in
// complex fields at runtime. The values of the map are the reflected types of the contained elements.
// They must be either primitive values from the plugin framework type system
// (types.String{}, types.Bool{}, types.Int64{}, types.Float64{}) or TF SDK values.
func (m StableUrl) GetComplexFieldTypes(ctx context.Context) map[string]reflect.Type {
	return map[string]reflect.Type{}
}

// ToObjectValue returns the object value for the resource, combining attributes from the
// embedded TFSDK model and contains additional fields.
//
// TFSDK types cannot implement the ObjectValuable interface directly, as it would otherwise
// interfere with how the plugin framework retrieves and sets values in state. Thus, StableUrl
// only implements ToObjectValue() and Type().
func (m StableUrl) ToObjectValue(ctx context.Context) basetypes.ObjectValue {
	return types.ObjectValueMust(
		m.Type(ctx).(basetypes.ObjectType).AttrTypes,
		map[string]attr.Value{"initial_workspace_id": m.InitialWorkspaceId,
			"name":          m.Name,
			"parent":        m.Parent,
			"stable_url_id": m.StableUrlId,
			"url":           m.Url,
		},
	)
}

// Type returns the object type with attributes from both the embedded TFSDK model
// and contains additional fields.
func (m StableUrl) Type(ctx context.Context) attr.Type {
	return types.ObjectType{
		AttrTypes: map[string]attr.Type{"initial_workspace_id": types.StringType,
			"name":          types.StringType,
			"parent":        types.StringType,
			"stable_url_id": types.StringType,
			"url":           types.StringType,
		},
	}
}

// SyncFieldsDuringCreateOrUpdate copies values from the plan into the receiver,
// including both embedded model fields and additional fields. This method is called
// during create and update.
func (to *StableUrl) SyncFieldsDuringCreateOrUpdate(ctx context.Context, from StableUrl) {
	if !from.InitialWorkspaceId.IsUnknown() && !from.InitialWorkspaceId.IsNull() {
		// InitialWorkspaceId is an input only field and not returned by the service, so we keep the value from the prior state.
		to.InitialWorkspaceId = from.InitialWorkspaceId
	}
	if !from.Parent.IsUnknown() {
		to.Parent = from.Parent
	}
	if !from.StableUrlId.IsUnknown() {
		to.StableUrlId = from.StableUrlId
	}
}

// SyncFieldsDuringRead copies values from the existing state into the receiver,
// including both embedded model fields and additional fields. This method is called
// during read.
func (to *StableUrl) SyncFieldsDuringRead(ctx context.Context, from StableUrl) {
	if !from.InitialWorkspaceId.IsUnknown() && !from.InitialWorkspaceId.IsNull() {
		// InitialWorkspaceId is an input only field and not returned by the service, so we keep the value from the prior state.
		to.InitialWorkspaceId = from.InitialWorkspaceId
	}
	if !from.Parent.IsUnknown() {
		to.Parent = from.Parent
	}
	if !from.StableUrlId.IsUnknown() {
		to.StableUrlId = from.StableUrlId
	}
}

func (m StableUrl) ApplySchemaCustomizations(attrs map[string]tfschema.AttributeBuilder) map[string]tfschema.AttributeBuilder {
	attrs["initial_workspace_id"] = attrs["initial_workspace_id"].SetRequired()
	attrs["initial_workspace_id"] = attrs["initial_workspace_id"].(tfschema.StringAttributeBuilder).AddPlanModifier(stringplanmodifier.RequiresReplace()).(tfschema.AttributeBuilder)
	attrs["name"] = attrs["name"].SetComputed()
	attrs["name"] = attrs["name"].(tfschema.StringAttributeBuilder).AddPlanModifier(stringplanmodifier.RequiresReplace()).(tfschema.AttributeBuilder)
	attrs["url"] = attrs["url"].SetComputed()
	attrs["url"] = attrs["url"].(tfschema.StringAttributeBuilder).AddPlanModifier(stringplanmodifier.UseStateForUnknown()).(tfschema.AttributeBuilder)
	attrs["stable_url_id"] = attrs["stable_url_id"].SetRequired()
	attrs["stable_url_id"] = attrs["stable_url_id"].(tfschema.StringAttributeBuilder).AddPlanModifier(stringplanmodifier.UseStateForUnknown()).(tfschema.AttributeBuilder)
	attrs["stable_url_id"] = attrs["stable_url_id"].(tfschema.StringAttributeBuilder).AddPlanModifier(stringplanmodifier.RequiresReplace()).(tfschema.AttributeBuilder)
	attrs["parent"] = attrs["parent"].SetRequired()
	attrs["parent"] = attrs["parent"].(tfschema.StringAttributeBuilder).AddPlanModifier(stringplanmodifier.RequiresReplace()).(tfschema.AttributeBuilder)

	attrs["name"] = attrs["name"].(tfschema.StringAttributeBuilder).AddPlanModifier(stringplanmodifier.UseStateForUnknown()).(tfschema.AttributeBuilder)
	return attrs
}

func (r *StableUrlResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = autogen.GetDatabricksProductionName(resourceName)
}

func (r *StableUrlResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs, blocks := tfschema.ResourceStructToSchemaMap(ctx, StableUrl{}, nil)
	resp.Schema = schema.Schema{
		Description: "Terraform schema for Databricks disaster_recovery_stable_url",
		Attributes:  attrs,
		Blocks:      blocks,
	}
}

func (r *StableUrlResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.Client = autogen.ConfigureResource(req, resp)
}

func (r *StableUrlResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = pluginfwcontext.SetUserAgentInResourceContext(ctx, resourceName)

	var plan StableUrl
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var stable_url disasterrecovery.StableUrl

	resp.Diagnostics.Append(converters.TfSdkToGoSdkStruct(ctx, plan, &stable_url)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createRequest := disasterrecovery.CreateStableUrlRequest{
		StableUrl:   stable_url,
		Parent:      plan.Parent.ValueString(),
		StableUrlId: plan.StableUrlId.ValueString(),
	}

	client, clientDiags := r.Client.GetAccountClient()

	resp.Diagnostics.Append(clientDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	response, err := client.DisasterRecovery.CreateStableUrl(ctx, createRequest)
	if err != nil {
		resp.Diagnostics.AddError("failed to create disaster_recovery_stable_url", err.Error())
		return
	}

	var newState StableUrl

	resp.Diagnostics.Append(converters.GoSdkToTfSdkStruct(ctx, response, &newState)...)

	if resp.Diagnostics.HasError() {
		return
	}

	newState.SyncFieldsDuringCreateOrUpdate(ctx, plan)

	resp.Diagnostics.Append(resp.State.Set(ctx, newState)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

func (r *StableUrlResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = pluginfwcontext.SetUserAgentInResourceContext(ctx, resourceName)

	var existingState StableUrl
	resp.Diagnostics.Append(req.State.Get(ctx, &existingState)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var readRequest disasterrecovery.GetStableUrlRequest
	resp.Diagnostics.Append(converters.TfSdkToGoSdkStruct(ctx, existingState, &readRequest)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client, clientDiags := r.Client.GetAccountClient()

	resp.Diagnostics.Append(clientDiags...)
	if resp.Diagnostics.HasError() {
		return
	}
	response, err := client.DisasterRecovery.GetStableUrl(ctx, readRequest)
	if err != nil {
		if apierr.IsMissing(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("failed to get disaster_recovery_stable_url", err.Error())
		return
	}

	var newState StableUrl
	resp.Diagnostics.Append(converters.GoSdkToTfSdkStruct(ctx, response, &newState)...)
	if resp.Diagnostics.HasError() {
		return
	}

	newState.SyncFieldsDuringRead(ctx, existingState)

	resp.Diagnostics.Append(resp.State.Set(ctx, newState)...)
}

func (r *StableUrlResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// VARIANT_IMMUTABLE resources do not support updates - all changes require replacement.
	resp.Diagnostics.AddError("Update not supported", "This resource does not support updates. All changes require replacement.")
}

func (r *StableUrlResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = pluginfwcontext.SetUserAgentInResourceContext(ctx, resourceName)

	var state StableUrl
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var deleteRequest disasterrecovery.DeleteStableUrlRequest
	resp.Diagnostics.Append(converters.TfSdkToGoSdkStruct(ctx, state, &deleteRequest)...)
	if resp.Diagnostics.HasError() {
		return
	}

	client, clientDiags := r.Client.GetAccountClient()

	resp.Diagnostics.Append(clientDiags...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := client.DisasterRecovery.DeleteStableUrl(ctx, deleteRequest)
	if !declarative.IsDeleteError(err) {
		err = nil
	}
	if err != nil && !apierr.IsMissing(err) {
		resp.Diagnostics.AddError("failed to delete disaster_recovery_stable_url", err.Error())
		return
	}

}

var _ resource.ResourceWithImportState = &StableUrlResource{}

func (r *StableUrlResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ",")

	if len(parts) != 1 || parts[0] == "" {
		resp.Diagnostics.AddError(
			"Unexpected Import Identifier",
			fmt.Sprintf(
				"Expected import identifier with format: name. Got: %q",
				req.ID,
			),
		)
		return
	}

	name := parts[0]
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
