// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package oauth2

import (
	"github.com/databricks/databricks-sdk-go/marshal"
)

type CreateCustomAppIntegration struct {
	// indicates if an oauth client-secret should be generated
	Confidential bool `tfsdk:"confidential"`
	// name of the custom oauth app
	Name string `tfsdk:"name"`
	// List of oauth redirect urls
	RedirectUrls []string `tfsdk:"redirect_urls"`
	// OAuth scopes granted to the application. Supported scopes: all-apis, sql,
	// offline_access, openid, profile, email.
	Scopes []string `tfsdk:"scopes"`
	// Token access policy
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *CreateCustomAppIntegration) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s CreateCustomAppIntegration) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

type CreateCustomAppIntegrationOutput struct {
	// oauth client-id generated by the Databricks
	ClientId string `tfsdk:"client_id"`
	// oauth client-secret generated by the Databricks if this is a confidential
	// oauth app client-secret will be generated.
	ClientSecret string `tfsdk:"client_secret"`
	// unique integration id for the custom oauth app
	IntegrationId string `tfsdk:"integration_id"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *CreateCustomAppIntegrationOutput) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s CreateCustomAppIntegrationOutput) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

type CreatePublishedAppIntegration struct {
	// app_id of the oauth published app integration. For example power-bi,
	// tableau-deskop
	AppId string `tfsdk:"app_id"`
	// Token access policy
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *CreatePublishedAppIntegration) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s CreatePublishedAppIntegration) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

type CreatePublishedAppIntegrationOutput struct {
	// unique integration id for the published oauth app
	IntegrationId string `tfsdk:"integration_id"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *CreatePublishedAppIntegrationOutput) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s CreatePublishedAppIntegrationOutput) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

// Create service principal secret
type CreateServicePrincipalSecretRequest struct {
	// The service principal ID.
	ServicePrincipalId int64 `tfsdk:"-" url:"-"`
}

type CreateServicePrincipalSecretResponse struct {
	// UTC time when the secret was created
	CreateTime string `tfsdk:"create_time"`
	// ID of the secret
	Id string `tfsdk:"id"`
	// Secret Value
	Secret string `tfsdk:"secret"`
	// Secret Hash
	SecretHash string `tfsdk:"secret_hash"`
	// Status of the secret
	Status string `tfsdk:"status"`
	// UTC time when the secret was updated
	UpdateTime string `tfsdk:"update_time"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *CreateServicePrincipalSecretResponse) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s CreateServicePrincipalSecretResponse) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

type DeleteCustomAppIntegrationOutput struct {
}

// Delete Custom OAuth App Integration
type DeleteCustomAppIntegrationRequest struct {
	// The oauth app integration ID.
	IntegrationId string `tfsdk:"-" url:"-"`
}

type DeletePublishedAppIntegrationOutput struct {
}

// Delete Published OAuth App Integration
type DeletePublishedAppIntegrationRequest struct {
	// The oauth app integration ID.
	IntegrationId string `tfsdk:"-" url:"-"`
}

type DeleteResponse struct {
}

// Delete service principal secret
type DeleteServicePrincipalSecretRequest struct {
	// The secret ID.
	SecretId string `tfsdk:"-" url:"-"`
	// The service principal ID.
	ServicePrincipalId int64 `tfsdk:"-" url:"-"`
}

type GetCustomAppIntegrationOutput struct {
	// oauth client id of the custom oauth app
	ClientId string `tfsdk:"client_id"`
	// indicates if an oauth client-secret should be generated
	Confidential bool `tfsdk:"confidential"`
	// ID of this custom app
	IntegrationId string `tfsdk:"integration_id"`
	// name of the custom oauth app
	Name string `tfsdk:"name"`
	// List of oauth redirect urls
	RedirectUrls []string `tfsdk:"redirect_urls"`
	// Token access policy
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *GetCustomAppIntegrationOutput) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s GetCustomAppIntegrationOutput) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

// Get OAuth Custom App Integration
type GetCustomAppIntegrationRequest struct {
	// The oauth app integration ID.
	IntegrationId string `tfsdk:"-" url:"-"`
}

type GetCustomAppIntegrationsOutput struct {
	// Array of Custom OAuth App Integrations defined for the account.
	Apps []GetCustomAppIntegrationOutput `tfsdk:"apps"`
}

type GetPublishedAppIntegrationOutput struct {
	// app-id of the published app integration
	AppId string `tfsdk:"app_id"`
	// unique integration id for the published oauth app
	IntegrationId string `tfsdk:"integration_id"`
	// name of the published oauth app
	Name string `tfsdk:"name"`
	// Token access policy
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *GetPublishedAppIntegrationOutput) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s GetPublishedAppIntegrationOutput) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

// Get OAuth Published App Integration
type GetPublishedAppIntegrationRequest struct {
	// The oauth app integration ID.
	IntegrationId string `tfsdk:"-" url:"-"`
}

type GetPublishedAppIntegrationsOutput struct {
	// Array of Published OAuth App Integrations defined for the account.
	Apps []GetPublishedAppIntegrationOutput `tfsdk:"apps"`
}

type GetPublishedAppsOutput struct {
	// Array of Published OAuth Apps.
	Apps []PublishedAppOutput `tfsdk:"apps"`
	// A token that can be used to get the next page of results. If not present,
	// there are no more results to show.
	NextPageToken string `tfsdk:"next_page_token"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *GetPublishedAppsOutput) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s GetPublishedAppsOutput) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

// Get all the published OAuth apps
type ListOAuthPublishedAppsRequest struct {
	// The max number of OAuth published apps to return.
	PageSize int64 `tfsdk:"-" url:"page_size,omitempty"`
	// A token that can be used to get the next page of results.
	PageToken string `tfsdk:"-" url:"page_token,omitempty"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *ListOAuthPublishedAppsRequest) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s ListOAuthPublishedAppsRequest) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

// List service principal secrets
type ListServicePrincipalSecretsRequest struct {
	// The service principal ID.
	ServicePrincipalId int64 `tfsdk:"-" url:"-"`
}

type ListServicePrincipalSecretsResponse struct {
	// List of the secrets
	Secrets []SecretInfo `tfsdk:"secrets"`
}

type PublishedAppOutput struct {
	// Unique ID of the published OAuth app.
	AppId string `tfsdk:"app_id"`
	// Client ID of the published OAuth app. It is the client_id in the OAuth
	// flow
	ClientId string `tfsdk:"client_id"`
	// Description of the published OAuth app.
	Description string `tfsdk:"description"`
	// Whether the published OAuth app is a confidential client. It is always
	// false for published OAuth apps.
	IsConfidentialClient bool `tfsdk:"is_confidential_client"`
	// Name of the published OAuth app.
	Name string `tfsdk:"name"`
	// Redirect URLs of the published OAuth app.
	RedirectUrls []string `tfsdk:"redirect_urls"`
	// Required scopes for the published OAuth app.
	Scopes []string `tfsdk:"scopes"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *PublishedAppOutput) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s PublishedAppOutput) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

type SecretInfo struct {
	// UTC time when the secret was created
	CreateTime string `tfsdk:"create_time"`
	// ID of the secret
	Id string `tfsdk:"id"`
	// Secret Hash
	SecretHash string `tfsdk:"secret_hash"`
	// Status of the secret
	Status string `tfsdk:"status"`
	// UTC time when the secret was updated
	UpdateTime string `tfsdk:"update_time"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *SecretInfo) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s SecretInfo) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

type TokenAccessPolicy struct {
	// access token time to live in minutes
	AccessTokenTtlInMinutes int `tfsdk:"access_token_ttl_in_minutes"`
	// refresh token time to live in minutes
	RefreshTokenTtlInMinutes int `tfsdk:"refresh_token_ttl_in_minutes"`

	ForceSendFields []string `tfsdk:"-"`
}

func (s *TokenAccessPolicy) UnmarshalJSON(b []byte) error {
	return marshal.Unmarshal(b, s)
}

func (s TokenAccessPolicy) MarshalJSON() ([]byte, error) {
	return marshal.Marshal(s)
}

type UpdateCustomAppIntegration struct {
	// The oauth app integration ID.
	IntegrationId string `tfsdk:"-" url:"-"`
	// List of oauth redirect urls to be updated in the custom oauth app
	// integration
	RedirectUrls []string `tfsdk:"redirect_urls"`
	// Token access policy to be updated in the custom oauth app integration
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`
}

type UpdateCustomAppIntegrationOutput struct {
}

type UpdatePublishedAppIntegration struct {
	// The oauth app integration ID.
	IntegrationId string `tfsdk:"-" url:"-"`
	// Token access policy to be updated in the published oauth app integration
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`
}

type UpdatePublishedAppIntegrationOutput struct {
}
