// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package oauth2

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CreateCustomAppIntegration struct {
	// indicates if an oauth client-secret should be generated
	Confidential types.Bool `tfsdk:"confidential"`
	// name of the custom oauth app
	Name types.String `tfsdk:"name"`
	// List of oauth redirect urls
	RedirectUrls types.List `tfsdk:"redirect_urls"`
	// OAuth scopes granted to the application. Supported scopes: all-apis, sql,
	// offline_access, openid, profile, email.
	Scopes types.List `tfsdk:"scopes"`
	// Token access policy
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`
}

type CreateCustomAppIntegrationOutput struct {
	// oauth client-id generated by the Databricks
	ClientId types.String `tfsdk:"client_id"`
	// oauth client-secret generated by the Databricks if this is a confidential
	// oauth app client-secret will be generated.
	ClientSecret types.String `tfsdk:"client_secret"`
	// unique integration id for the custom oauth app
	IntegrationId types.String `tfsdk:"integration_id"`
}

type CreatePublishedAppIntegration struct {
	// app_id of the oauth published app integration. For example power-bi,
	// tableau-deskop
	AppId types.String `tfsdk:"app_id"`
	// Token access policy
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`
}

type CreatePublishedAppIntegrationOutput struct {
	// unique integration id for the published oauth app
	IntegrationId types.String `tfsdk:"integration_id"`
}

// Create service principal secret
type CreateServicePrincipalSecretRequest struct {
	// The service principal ID.
	ServicePrincipalId types.Int64 `tfsdk:"-" url:"-"`
}

type CreateServicePrincipalSecretResponse struct {
	// UTC time when the secret was created
	CreateTime types.String `tfsdk:"create_time"`
	// ID of the secret
	Id types.String `tfsdk:"id"`
	// Secret Value
	Secret types.String `tfsdk:"secret"`
	// Secret Hash
	SecretHash types.String `tfsdk:"secret_hash"`
	// Status of the secret
	Status types.String `tfsdk:"status"`
	// UTC time when the secret was updated
	UpdateTime types.String `tfsdk:"update_time"`
}

type DataPlaneInfo struct {
	// Authorization details as a string.
	AuthorizationDetails types.String `tfsdk:"authorization_details"`
	// The URL of the endpoint for this operation in the dataplane.
	EndpointUrl types.String `tfsdk:"endpoint_url"`
}

type DeleteCustomAppIntegrationOutput struct {
}

// Delete Custom OAuth App Integration
type DeleteCustomAppIntegrationRequest struct {
	// The oauth app integration ID.
	IntegrationId types.String `tfsdk:"-" url:"-"`
}

type DeletePublishedAppIntegrationOutput struct {
}

// Delete Published OAuth App Integration
type DeletePublishedAppIntegrationRequest struct {
	// The oauth app integration ID.
	IntegrationId types.String `tfsdk:"-" url:"-"`
}

type DeleteResponse struct {
}

// Delete service principal secret
type DeleteServicePrincipalSecretRequest struct {
	// The secret ID.
	SecretId types.String `tfsdk:"-" url:"-"`
	// The service principal ID.
	ServicePrincipalId types.Int64 `tfsdk:"-" url:"-"`
}

type GetCustomAppIntegrationOutput struct {
	// oauth client id of the custom oauth app
	ClientId types.String `tfsdk:"client_id"`
	// indicates if an oauth client-secret should be generated
	Confidential types.Bool `tfsdk:"confidential"`
	// ID of this custom app
	IntegrationId types.String `tfsdk:"integration_id"`
	// name of the custom oauth app
	Name types.String `tfsdk:"name"`
	// List of oauth redirect urls
	RedirectUrls types.List `tfsdk:"redirect_urls"`
	// Token access policy
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`
}

// Get OAuth Custom App Integration
type GetCustomAppIntegrationRequest struct {
	// The oauth app integration ID.
	IntegrationId types.String `tfsdk:"-" url:"-"`
}

type GetCustomAppIntegrationsOutput struct {
	// Array of Custom OAuth App Integrations defined for the account.
	Apps types.List `tfsdk:"apps"`
}

type GetPublishedAppIntegrationOutput struct {
	// app-id of the published app integration
	AppId types.String `tfsdk:"app_id"`
	// unique integration id for the published oauth app
	IntegrationId types.String `tfsdk:"integration_id"`
	// name of the published oauth app
	Name types.String `tfsdk:"name"`
	// Token access policy
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`
}

// Get OAuth Published App Integration
type GetPublishedAppIntegrationRequest struct {
	// The oauth app integration ID.
	IntegrationId types.String `tfsdk:"-" url:"-"`
}

type GetPublishedAppIntegrationsOutput struct {
	// Array of Published OAuth App Integrations defined for the account.
	Apps types.List `tfsdk:"apps"`
}

type GetPublishedAppsOutput struct {
	// Array of Published OAuth Apps.
	Apps types.List `tfsdk:"apps"`
	// A token that can be used to get the next page of results. If not present,
	// there are no more results to show.
	NextPageToken types.String `tfsdk:"next_page_token"`
}

// Get all the published OAuth apps
type ListOAuthPublishedAppsRequest struct {
	// The max number of OAuth published apps to return.
	PageSize types.Int64 `tfsdk:"-" url:"page_size,omitempty"`
	// A token that can be used to get the next page of results.
	PageToken types.String `tfsdk:"-" url:"page_token,omitempty"`
}

// List service principal secrets
type ListServicePrincipalSecretsRequest struct {
	// The service principal ID.
	ServicePrincipalId types.Int64 `tfsdk:"-" url:"-"`
}

type ListServicePrincipalSecretsResponse struct {
	// List of the secrets
	Secrets types.List `tfsdk:"secrets"`
}

type PublishedAppOutput struct {
	// Unique ID of the published OAuth app.
	AppId types.String `tfsdk:"app_id"`
	// Client ID of the published OAuth app. It is the client_id in the OAuth
	// flow
	ClientId types.String `tfsdk:"client_id"`
	// Description of the published OAuth app.
	Description types.String `tfsdk:"description"`
	// Whether the published OAuth app is a confidential client. It is always
	// false for published OAuth apps.
	IsConfidentialClient types.Bool `tfsdk:"is_confidential_client"`
	// Name of the published OAuth app.
	Name types.String `tfsdk:"name"`
	// Redirect URLs of the published OAuth app.
	RedirectUrls types.List `tfsdk:"redirect_urls"`
	// Required scopes for the published OAuth app.
	Scopes types.List `tfsdk:"scopes"`
}

type SecretInfo struct {
	// UTC time when the secret was created
	CreateTime types.String `tfsdk:"create_time"`
	// ID of the secret
	Id types.String `tfsdk:"id"`
	// Secret Hash
	SecretHash types.String `tfsdk:"secret_hash"`
	// Status of the secret
	Status types.String `tfsdk:"status"`
	// UTC time when the secret was updated
	UpdateTime types.String `tfsdk:"update_time"`
}

type TokenAccessPolicy struct {
	// access token time to live in minutes
	AccessTokenTtlInMinutes types.Int64 `tfsdk:"access_token_ttl_in_minutes"`
	// refresh token time to live in minutes
	RefreshTokenTtlInMinutes types.Int64 `tfsdk:"refresh_token_ttl_in_minutes"`
}

type UpdateCustomAppIntegration struct {
	// The oauth app integration ID.
	IntegrationId types.String `tfsdk:"-" url:"-"`
	// List of oauth redirect urls to be updated in the custom oauth app
	// integration
	RedirectUrls types.List `tfsdk:"redirect_urls"`
	// Token access policy to be updated in the custom oauth app integration
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`
}

type UpdateCustomAppIntegrationOutput struct {
}

type UpdatePublishedAppIntegration struct {
	// The oauth app integration ID.
	IntegrationId types.String `tfsdk:"-" url:"-"`
	// Token access policy to be updated in the published oauth app integration
	TokenAccessPolicy *TokenAccessPolicy `tfsdk:"token_access_policy"`
}

type UpdatePublishedAppIntegrationOutput struct {
}
