// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package pluginfw

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// List of resources that are auto generated based on service OpenAPI specs.
var autoGeneratedResources = []func() resource.Resource{}

// List of data sources that are auto generated based on service OpenAPI specs.
var autoGeneratedDataSources = []func() datasource.DataSource{}
