// Code generated from OpenAPI specs by Databricks SDK Generator. DO NOT EDIT.

package pluginfw

import (
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/alert_v2"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/budget_policy"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/clean_room_asset_revisions_clean_room_asset"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/clean_room_asset"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/clean_room_auto_approval_rule"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/clean_rooms_clean_room"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/database_instance"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/database_database_catalog"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/external_metadata"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/online_store"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/materialized_features_feature_tag"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/account_network_policy"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/quality_monitor_v2"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/recipient_federation_policy"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/request_for_access"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/account_setting"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/workspace_network_option"

	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/workspace_setting"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// List of resources that are auto generated based on service OpenAPI specs.
var autoGeneratedResources = []func() resource.Resource{
	alert_v2.ResourceAlertV2,
	budget_policy.ResourceBudgetPolicy,
	clean_room_asset.ResourceCleanRoomAsset,
	clean_room_auto_approval_rule.ResourceCleanRoomAutoApprovalRule,
	clean_rooms_clean_room.ResourceCleanRoom,
	database_instance.ResourceDatabaseInstance,
	database_database_catalog.ResourceDatabaseCatalog,
	external_metadata.ResourceExternalMetadata,
	online_store.ResourceOnlineStore,
	materialized_features_feature_tag.ResourceFeatureTag,
	account_network_policy.ResourceAccountNetworkPolicy,
	quality_monitor_v2.ResourceQualityMonitor,
	recipient_federation_policy.ResourceFederationPolicy,
	request_for_access.ResourceAccessRequestDestination,
	account_setting.ResourceSetting,
	workspace_network_option.ResourceWorkspaceNetworkOption,
	workspace_setting.ResourceSetting,
}

// List of data sources that are auto generated based on service OpenAPI specs.
var autoGeneratedDataSources = []func() datasource.DataSource{
	alert_v2.DataSourceAlertV2,
	budget_policy.DataSourceBudgetPolicy,
	clean_room_asset_revisions_clean_room_asset.DataSourceCleanRoomAsset,
	clean_room_asset.DataSourceCleanRoomAsset,
	clean_room_auto_approval_rule.DataSourceCleanRoomAutoApprovalRule,
	clean_rooms_clean_room.DataSourceCleanRoom,
	database_instance.DataSourceDatabaseInstance,
	database_database_catalog.DataSourceDatabaseCatalog,
	external_metadata.DataSourceExternalMetadata,
	online_store.DataSourceOnlineStore,
	materialized_features_feature_tag.DataSourceFeatureTag,
	account_network_policy.DataSourceAccountNetworkPolicy,
	quality_monitor_v2.DataSourceQualityMonitor,
	recipient_federation_policy.DataSourceFederationPolicy,
	request_for_access.DataSourceAccessRequestDestination,
	account_setting.DataSourceSetting,
	workspace_network_option.DataSourceWorkspaceNetworkOption,
	workspace_setting.DataSourceSetting,
	alert_v2.DataSourceAlertsV2,
	budget_policy.DataSourceBudgetPolicies,
	clean_room_asset_revisions_clean_room_asset.DataSourceCleanRoomAssets,
	clean_room_asset.DataSourceCleanRoomAssets,
	clean_room_auto_approval_rule.DataSourceCleanRoomAutoApprovalRules,
	clean_rooms_clean_room.DataSourceCleanRooms,
	database_instance.DataSourceDatabaseInstances,
	database_database_catalog.DataSourceDatabaseCatalogs,
	external_metadata.DataSourceExternalMetadatas,
	online_store.DataSourceOnlineStores,
	materialized_features_feature_tag.DataSourceFeatureTags,
	account_network_policy.DataSourceAccountNetworkPolicies,
	quality_monitor_v2.DataSourceQualityMonitors,
	recipient_federation_policy.DataSourceFederationPolicies,
}
