package pluginfw

// This file contains all of the utils for controlling the plugin framework rollout.
//
// Resources and data sources move through two rollout lists:
//
//   - migratedResources / migratedDataSources: served by the plugin framework
//     by default. Users can fall back to SDK V2 per-resource via the
//     USE_SDK_V2_RESOURCES / USE_SDK_V2_DATA_SOURCES environment variables.
//     Example: USE_SDK_V2_RESOURCES="databricks_library"
//
//   - pluginFwOptInResources / pluginFwOptInDataSources: served by SDK V2 by
//     default. Users opt into the plugin framework implementation per-resource
//     via the DATABRICKS_TF_ENABLED_PF_RESOURCES /
//     DATABRICKS_TF_ENABLED_PF_DATA_SOURCES environment variables.
//     Example: DATABRICKS_TF_ENABLED_PF_RESOURCES="databricks_mws_ncc_private_endpoint_rule"
//
// The two env vars operate on disjoint sets: a name is consulted only in the
// list it appears in.

import (
	"context"
	"log"
	"os"
	"slices"
	"strings"

	"github.com/databricks/databricks-sdk-go/config"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/app"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/catalog"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/cluster"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/dashboards"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/library"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/networks/privateendpointrule"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/notificationdestinations"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/qualitymonitor"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/registered_model"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/serving"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/sharing"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/user"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/volume"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// List of resources that have been migrated from SDK V2 to plugin framework.
// The SDKv2 fallback path (selected via USE_SDK_V2_RESOURCES) is deprecated and
// will be removed in the next major release; getPluginFrameworkResourcesToRegister
// logs a [WARN] line whenever a name in this list is steered back to SDKv2.
// Keep this list sorted.
var migratedResources = []func() resource.Resource{
	library.ResourceLibrary,
	qualitymonitor.ResourceQualityMonitor,
	sharing.ResourceShare,
}

// List of data sources that have been migrated from SDK V2 to plugin framework.
// The SDKv2 fallback path (selected via USE_SDK_V2_DATA_SOURCES) is deprecated
// and will be removed in the next major release.
// Keep this list sorted.
var migratedDataSources = []func() datasource.DataSource{
	sharing.DataSourceShare,
	sharing.DataSourceShares,
	volume.DataSourceVolumes,
}

// List of resources whose plugin framework implementation is available but
// gated behind the DATABRICKS_TF_ENABLED_PF_RESOURCES env var. The SDK V2
// implementation remains the default. Promote to migratedResources once the
// opt-in implementation has been validated by users.
// Keep this list sorted.
var pluginFwOptInResources = []func() resource.Resource{
	privateendpointrule.ResourcePrivateEndpointRule,
}

// List of data sources gated behind DATABRICKS_TF_ENABLED_PF_DATA_SOURCES,
// the data source equivalent of pluginFwOptInResources.
// Keep this list sorted.
var pluginFwOptInDataSources = []func() datasource.DataSource{}

// List of resources that have been onboarded to the plugin framework - not migrated from sdkv2.
// Keep this list sorted.
var pluginFwOnlyResources = append(
	[]func() resource.Resource{
		app.ResourceApp,
	},
	autoGeneratedResources...,
)

// List of data sources that have been onboarded to the plugin framework - not migrated from sdkv2.
// Keep this list sorted.
var pluginFwOnlyDataSources = append(
	[]func() datasource.DataSource{
		app.DataSourceApp,
		app.DataSourceApps,
		catalog.DataSourceFunctions,
		dashboards.DataSourceDashboards,
		notificationdestinations.DataSourceNotificationDestinations,
		registered_model.DataSourceRegisteredModel,
		registered_model.DataSourceRegisteredModelVersions,
		serving.DataSourceServingEndpoints,
		user.DataSourceUsers,
		// TODO: Add DataSourceCluster into migratedDataSources after fixing unit tests.
		cluster.DataSourceCluster, // Using the staging name (with pluginframework suffix)
	},
	autoGeneratedDataSources...,
)

type pluginFrameworkOptions struct {
	resourceFallbacks   []string
	dataSourceFallbacks []string
	resourceOptIns      []string
	dataSourceOptIns    []string
	configCustomizer    func(*config.Config) error
}

// PluginFrameworkOption is an interface for acceptance tests to specify resources / data sources to fallback to SDK V2
type PluginFrameworkOption interface {
	Apply(*pluginFrameworkOptions)
}

type sdkV2ResourceFallback struct {
	resourceFallbacks []string
}

func (o *sdkV2ResourceFallback) Apply(options *pluginFrameworkOptions) {
	options.resourceFallbacks = o.resourceFallbacks
}

// WithSdkV2ResourceFallbacks is a helper function to specify resources to fallback to SDK V2
func WithSdkV2ResourceFallbacks(fallbacks []string) PluginFrameworkOption {
	return &sdkV2ResourceFallback{resourceFallbacks: fallbacks}
}

type sdkv2DataSourceFallback struct {
	dataSourceFallbacks []string
}

func (o *sdkv2DataSourceFallback) Apply(options *pluginFrameworkOptions) {
	options.dataSourceFallbacks = o.dataSourceFallbacks
}

// WithSdkV2DataSourceFallbacks is a helper function to specify data sources to fallback to SDK V2
func WithSdkV2DataSourceFallbacks(fallbacks []string) PluginFrameworkOption {
	return &sdkv2DataSourceFallback{dataSourceFallbacks: fallbacks}
}

type pluginFrameworkResourceOptIn struct {
	resources []string
}

func (o *pluginFrameworkResourceOptIn) Apply(options *pluginFrameworkOptions) {
	options.resourceOptIns = o.resources
}

// WithPluginFrameworkResources force-enables opt-in plugin framework resources
// regardless of the DATABRICKS_TF_ENABLED_PF_RESOURCES env var. Used by
// acceptance tests to exercise the PF implementation deterministically.
func WithPluginFrameworkResources(resources []string) PluginFrameworkOption {
	return &pluginFrameworkResourceOptIn{resources: resources}
}

type pluginFrameworkDataSourceOptIn struct {
	dataSources []string
}

func (o *pluginFrameworkDataSourceOptIn) Apply(options *pluginFrameworkOptions) {
	options.dataSourceOptIns = o.dataSources
}

// WithPluginFrameworkDataSources is the data source counterpart of
// WithPluginFrameworkResources.
func WithPluginFrameworkDataSources(dataSources []string) PluginFrameworkOption {
	return &pluginFrameworkDataSourceOptIn{dataSources: dataSources}
}

type configCustomizer struct {
	configCustomizer func(*config.Config) error
}

func (o *configCustomizer) Apply(options *pluginFrameworkOptions) {
	options.configCustomizer = o.configCustomizer
}

// WithConfigCustomizer allows the caller to customize the SDK config before config resolution,
// so customizer-set fields (e.g. Host) participate in resolveHostMetadata and auth.
func WithConfigCustomizer(customizer func(*config.Config) error) PluginFrameworkOption {
	return &configCustomizer{configCustomizer: customizer}
}

// splitEnvList parses a comma-separated environment variable into resource
// names, trimming surrounding whitespace and dropping empty entries so that
// "a, b" and "a,b" behave identically and a stray trailing comma is harmless.
func splitEnvList(value string) []string {
	names := []string{}
	for _, part := range strings.Split(value, ",") {
		if trimmed := strings.TrimSpace(part); trimmed != "" {
			names = append(names, trimmed)
		}
	}
	return names
}

// GetUseSdkV2DataSources is a helper function to get name of resources that should use SDK V2 instead of plugin framework
func getUseSdkV2Resources() []string {
	return splitEnvList(os.Getenv("USE_SDK_V2_RESOURCES"))
}

// GetUseSdkV2DataSources is a helper function to get name of data sources that should use SDK V2 instead of plugin framework
func getUseSdkV2DataSources() []string {
	return splitEnvList(os.Getenv("USE_SDK_V2_DATA_SOURCES"))
}

// Helper function to check if a resource should use be in SDK V2 instead of plugin framework
func shouldUseSdkV2Resource(resourceName string) bool {
	useSdkV2Resources := getUseSdkV2Resources()
	return slices.Contains(useSdkV2Resources, resourceName)
}

// Helper function to check if a data source should use be in SDK V2 instead of plugin framework
func shouldUseSdkV2DataSource(dataSourceName string) bool {
	sdkV2DataSources := getUseSdkV2DataSources()
	return slices.Contains(sdkV2DataSources, dataSourceName)
}

// getEnabledPluginFrameworkResources returns the names of opt-in plugin
// framework resources that the user has enabled via the
// DATABRICKS_TF_ENABLED_PF_RESOURCES environment variable.
func getEnabledPluginFrameworkResources() []string {
	return splitEnvList(os.Getenv("DATABRICKS_TF_ENABLED_PF_RESOURCES"))
}

// getEnabledPluginFrameworkDataSources is the data source counterpart of
// getEnabledPluginFrameworkResources.
func getEnabledPluginFrameworkDataSources() []string {
	return splitEnvList(os.Getenv("DATABRICKS_TF_ENABLED_PF_DATA_SOURCES"))
}

// shouldUsePluginFrameworkResource reports whether the user has opted into the
// plugin framework implementation of a resource from pluginFwOptInResources.
func shouldUsePluginFrameworkResource(resourceName string) bool {
	return slices.Contains(getEnabledPluginFrameworkResources(), resourceName)
}

// shouldUsePluginFrameworkDataSource is the data source counterpart of
// shouldUsePluginFrameworkResource.
func shouldUsePluginFrameworkDataSource(dataSourceName string) bool {
	return slices.Contains(getEnabledPluginFrameworkDataSources(), dataSourceName)
}

// getPluginFrameworkResourcesToRegister returns the resources that the plugin
// framework provider should register. resourceFallbacks force-excludes a
// migrated resource (used by acceptance tests); pluginFrameworkOptIns
// force-includes an opt-in resource (also used by acceptance tests, mirroring
// DATABRICKS_TF_ENABLED_PF_RESOURCES).
func getPluginFrameworkResourcesToRegister(resourceFallbacks, pluginFrameworkOptIns []string) []func() resource.Resource {
	var resources []func() resource.Resource

	// migratedResources are PF by default; users / tests can opt out.
	for _, resourceFunc := range migratedResources {
		name := getResourceName(resourceFunc)
		if !shouldUseSdkV2Resource(name) && !slices.Contains(resourceFallbacks, name) {
			resources = append(resources, resourceFunc)
		} else {
			log.Printf("[WARN] resource %q is using the deprecated SDKv2 implementation; "+
				"this fallback will be removed in the next major release. Unset "+
				"USE_SDK_V2_RESOURCES to use the Plugin Framework version.", name)
		}
	}

	// pluginFwOptInResources are SDK V2 by default; users / tests can opt in.
	for _, resourceFunc := range pluginFwOptInResources {
		name := getResourceName(resourceFunc)
		if shouldUsePluginFrameworkResource(name) || slices.Contains(pluginFrameworkOptIns, name) {
			resources = append(resources, resourceFunc)
		}
	}

	return append(resources, pluginFwOnlyResources...)
}

// getPluginFrameworkDataSourcesToRegister is the data source counterpart of
// getPluginFrameworkResourcesToRegister.
func getPluginFrameworkDataSourcesToRegister(dataSourceFallbacks, pluginFrameworkOptIns []string) []func() datasource.DataSource {
	var dataSources []func() datasource.DataSource

	for _, dataSourceFunc := range migratedDataSources {
		name := getDataSourceName(dataSourceFunc)
		if !shouldUseSdkV2DataSource(name) && !slices.Contains(dataSourceFallbacks, name) {
			dataSources = append(dataSources, dataSourceFunc)
		} else {
			log.Printf("[WARN] data source %q is using the deprecated SDKv2 implementation; "+
				"this fallback will be removed in the next major release. Unset "+
				"USE_SDK_V2_DATA_SOURCES to use the Plugin Framework version.", name)
		}
	}

	for _, dataSourceFunc := range pluginFwOptInDataSources {
		name := getDataSourceName(dataSourceFunc)
		if shouldUsePluginFrameworkDataSource(name) || slices.Contains(pluginFrameworkOptIns, name) {
			dataSources = append(dataSources, dataSourceFunc)
		}
	}

	return append(dataSources, pluginFwOnlyDataSources...)
}

func getResourceName(resourceFunc func() resource.Resource) string {
	resp := resource.MetadataResponse{}
	resourceFunc().Metadata(context.Background(), resource.MetadataRequest{ProviderTypeName: "databricks"}, &resp)
	return resp.TypeName
}

func getDataSourceName(dataSourceFunc func() datasource.DataSource) string {
	resp := datasource.MetadataResponse{}
	dataSourceFunc().Metadata(context.Background(), datasource.MetadataRequest{ProviderTypeName: "databricks"}, &resp)
	return resp.TypeName
}

// PluginFrameworkOptInResourceNames returns the resource type names of all
// opt-in plugin framework resources. Exposed for cross-package invariant
// tests; production code should not need this.
func PluginFrameworkOptInResourceNames() []string {
	names := make([]string, 0, len(pluginFwOptInResources))
	for _, f := range pluginFwOptInResources {
		names = append(names, getResourceName(f))
	}
	return names
}

// PluginFrameworkOptInDataSourceNames is the data source counterpart of
// PluginFrameworkOptInResourceNames.
func PluginFrameworkOptInDataSourceNames() []string {
	names := make([]string, 0, len(pluginFwOptInDataSources))
	for _, f := range pluginFwOptInDataSources {
		names = append(names, getDataSourceName(f))
	}
	return names
}

// GetSdkV2ResourcesToRemove returns the resources the SDK V2 provider should
// drop from its resource map so they don't collide with the plugin framework
// registrations. This is the inverse of getPluginFrameworkResourcesToRegister:
// migrated resources that haven't been opted out, plus opt-in resources that
// the user has enabled.
func GetSdkV2ResourcesToRemove(resourceFallbacks, pluginFrameworkOptIns []string) []string {
	resourcesToRemove := []string{}
	for _, resourceFunc := range migratedResources {
		name := getResourceName(resourceFunc)
		if !shouldUseSdkV2Resource(name) && !slices.Contains(resourceFallbacks, name) {
			resourcesToRemove = append(resourcesToRemove, name)
		}
	}
	for _, resourceFunc := range pluginFwOptInResources {
		name := getResourceName(resourceFunc)
		if shouldUsePluginFrameworkResource(name) || slices.Contains(pluginFrameworkOptIns, name) {
			resourcesToRemove = append(resourcesToRemove, name)
		}
	}
	return resourcesToRemove
}

// GetSdkV2DataSourcesToRemove is the data source counterpart of
// GetSdkV2ResourcesToRemove.
func GetSdkV2DataSourcesToRemove(dataSourceFallbacks, pluginFrameworkOptIns []string) []string {
	dataSourcesToRemove := []string{}
	for _, dataSourceFunc := range migratedDataSources {
		name := getDataSourceName(dataSourceFunc)
		if !shouldUseSdkV2DataSource(name) && !slices.Contains(dataSourceFallbacks, name) {
			dataSourcesToRemove = append(dataSourcesToRemove, name)
		}
	}
	for _, dataSourceFunc := range pluginFwOptInDataSources {
		name := getDataSourceName(dataSourceFunc)
		if shouldUsePluginFrameworkDataSource(name) || slices.Contains(pluginFrameworkOptIns, name) {
			dataSourcesToRemove = append(dataSourcesToRemove, name)
		}
	}
	return dataSourcesToRemove
}
