package pluginfw

// This file contains all of the utils for controlling the plugin framework rollout.
// For migrated resources and data sources, we can add them to the two maps below to have them registered with the plugin framework.
// The acceptance test infrastructure can pin specific names back to SDKv2 via the
// WithSdkV2ResourceFallbacks / WithSdkV2DataSourceFallbacks options for
// transition-from-SDKv2 tests; this hook is not exposed to end users.

import (
	"context"
	"slices"

	"github.com/databricks/databricks-sdk-go/config"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/app"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/catalog"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/cluster"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/dashboards"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/library"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/notificationdestinations"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/qualitymonitor"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/registered_model"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/serving"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/sharing"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/user"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/volume"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// List of resources that have been migrated from SDK V2 to plugin framework.
// Acceptance tests can pin specific names back to SDKv2 via WithSdkV2ResourceFallbacks
// to exercise the transition-from-SDKv2 path; production usage always serves these from PF.
// Keep this list sorted.
var migratedResources = []func() resource.Resource{
	library.ResourceLibrary,
	qualitymonitor.ResourceQualityMonitor,
	sharing.ResourceShare,
}

// List of data sources that have been migrated from SDK V2 to plugin framework.
// See migratedResources for the SDKv2 fallback contract.
// Keep this list sorted.
var migratedDataSources = []func() datasource.DataSource{
	sharing.DataSourceShare,
	sharing.DataSourceShares,
	volume.DataSourceVolumes,
}

// List of resources that have been onboarded to the plugin framework - not migrated from sdkv2.
// Keep this list sorted.
var pluginFwOnlyResources = append(
	[]func() resource.Resource{
		app.ResourceApp,
	},
	autoGeneratedResources...,
)

// List of data sources that have been onboarded to the plugin framework - not migrated from sdkv2.
// Keep this list sorted.
var pluginFwOnlyDataSources = append(
	[]func() datasource.DataSource{
		app.DataSourceApp,
		app.DataSourceApps,
		catalog.DataSourceFunctions,
		dashboards.DataSourceDashboards,
		notificationdestinations.DataSourceNotificationDestinations,
		registered_model.DataSourceRegisteredModel,
		registered_model.DataSourceRegisteredModelVersions,
		serving.DataSourceServingEndpoints,
		user.DataSourceUsers,
		// TODO: Add DataSourceCluster into migratedDataSources after fixing unit tests.
		cluster.DataSourceCluster, // Using the staging name (with pluginframework suffix)
	},
	autoGeneratedDataSources...,
)

type pluginFrameworkOptions struct {
	resourceFallbacks   []string
	dataSourceFallbacks []string
	configCustomizer    func(*config.Config) error
}

// PluginFrameworkOption is an interface for acceptance tests to specify resources / data sources to fallback to SDK V2
type PluginFrameworkOption interface {
	Apply(*pluginFrameworkOptions)
}

type sdkV2ResourceFallback struct {
	resourceFallbacks []string
}

func (o *sdkV2ResourceFallback) Apply(options *pluginFrameworkOptions) {
	options.resourceFallbacks = o.resourceFallbacks
}

// WithSdkV2ResourceFallbacks is a helper function to specify resources to fallback to SDK V2
func WithSdkV2ResourceFallbacks(fallbacks []string) PluginFrameworkOption {
	return &sdkV2ResourceFallback{resourceFallbacks: fallbacks}
}

type sdkv2DataSourceFallback struct {
	dataSourceFallbacks []string
}

func (o *sdkv2DataSourceFallback) Apply(options *pluginFrameworkOptions) {
	options.dataSourceFallbacks = o.dataSourceFallbacks
}

// WithSdkV2DataSourceFallbacks is a helper function to specify data sources to fallback to SDK V2
func WithSdkV2DataSourceFallbacks(fallbacks []string) PluginFrameworkOption {
	return &sdkv2DataSourceFallback{dataSourceFallbacks: fallbacks}
}

type configCustomizer struct {
	configCustomizer func(*config.Config) error
}

func (o *configCustomizer) Apply(options *pluginFrameworkOptions) {
	options.configCustomizer = o.configCustomizer
}

// WithConfigCustomizer allows the caller to customize the SDK config before config resolution,
// so customizer-set fields (e.g. Host) participate in resolveHostMetadata and auth.
func WithConfigCustomizer(customizer func(*config.Config) error) PluginFrameworkOption {
	return &configCustomizer{configCustomizer: customizer}
}

// getPluginFrameworkResourcesToRegister is a helper function to get the list of resources that are migrated away from sdkv2 to plugin framework
func getPluginFrameworkResourcesToRegister(resourceFallbacks []string) []func() resource.Resource {
	var resources []func() resource.Resource

	// Skip resources pinned to SDKv2 via WithSdkV2ResourceFallbacks (acceptance tests only).
	for _, resourceFunc := range migratedResources {
		name := getResourceName(resourceFunc)
		if !slices.Contains(resourceFallbacks, name) {
			resources = append(resources, resourceFunc)
		}
	}

	return append(resources, pluginFwOnlyResources...)
}

// getPluginFrameworkDataSourcesToRegister is a helper function to get the list of data sources that are migrated away from sdkv2 to plugin framework
func getPluginFrameworkDataSourcesToRegister(dataSourceFallbacks []string) []func() datasource.DataSource {
	var dataSources []func() datasource.DataSource

	// Skip data sources pinned to SDKv2 via WithSdkV2DataSourceFallbacks (acceptance tests only).
	for _, dataSourceFunc := range migratedDataSources {
		name := getDataSourceName(dataSourceFunc)
		if !slices.Contains(dataSourceFallbacks, name) {
			dataSources = append(dataSources, dataSourceFunc)
		}
	}

	return append(dataSources, pluginFwOnlyDataSources...)
}

func getResourceName(resourceFunc func() resource.Resource) string {
	resp := resource.MetadataResponse{}
	resourceFunc().Metadata(context.Background(), resource.MetadataRequest{ProviderTypeName: "databricks"}, &resp)
	return resp.TypeName
}

func getDataSourceName(dataSourceFunc func() datasource.DataSource) string {
	resp := datasource.MetadataResponse{}
	dataSourceFunc().Metadata(context.Background(), datasource.MetadataRequest{ProviderTypeName: "databricks"}, &resp)
	return resp.TypeName
}

// GetSdkV2ResourcesToRemove returns the list of resource names that the SDKv2
// provider should drop from its resource map because they are now served by
// the Plugin Framework. Names listed in resourceFallbacks stay on SDKv2; that
// hook is for acceptance tests only.
func GetSdkV2ResourcesToRemove(resourceFallbacks []string) []string {
	resourcesToRemove := []string{}
	for _, resourceFunc := range migratedResources {
		name := getResourceName(resourceFunc)
		if !slices.Contains(resourceFallbacks, name) {
			resourcesToRemove = append(resourcesToRemove, name)
		}
	}
	return resourcesToRemove
}

// GetSdkV2DataSourcesToRemove is the data-source counterpart to GetSdkV2ResourcesToRemove.
func GetSdkV2DataSourcesToRemove(dataSourceFallbacks []string) []string {
	dataSourcesToRemove := []string{}
	for _, dataSourceFunc := range migratedDataSources {
		name := getDataSourceName(dataSourceFunc)
		if !slices.Contains(dataSourceFallbacks, name) {
			dataSourcesToRemove = append(dataSourcesToRemove, name)
		}
	}
	return dataSourcesToRemove
}
