package pluginfw

// This file contains the lists of resources and data sources registered with
// the Plugin Framework provider. The Plugin Framework is the only path; the
// SDKv2 fallback (USE_SDK_V2_* env vars and WithSdkV2*Fallbacks options) was
// removed once the migrated resources stabilized.

import (
	"github.com/databricks/databricks-sdk-go/config"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/app"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/catalog"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/cluster"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/dashboards"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/library"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/notificationdestinations"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/qualitymonitor"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/registered_model"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/serving"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/sharing"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/user"
	"github.com/databricks/terraform-provider-databricks/internal/providers/pluginfw/products/volume"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// pluginFwResources is the full set of resources served by the Plugin Framework
// provider, including the formerly-migrated databricks_library /
// databricks_quality_monitor / databricks_share.
// Keep this list sorted.
var pluginFwResources = append(
	[]func() resource.Resource{
		app.ResourceApp,
		library.ResourceLibrary,
		qualitymonitor.ResourceQualityMonitor,
		sharing.ResourceShare,
	},
	autoGeneratedResources...,
)

// pluginFwDataSources is the full set of data sources served by the Plugin
// Framework provider, including the formerly-migrated databricks_share /
// databricks_shares / databricks_volumes.
// Keep this list sorted.
var pluginFwDataSources = append(
	[]func() datasource.DataSource{
		app.DataSourceApp,
		app.DataSourceApps,
		catalog.DataSourceFunctions,
		// TODO: Add DataSourceCluster after fixing unit tests.
		cluster.DataSourceCluster, // Using the staging name (with pluginframework suffix)
		dashboards.DataSourceDashboards,
		notificationdestinations.DataSourceNotificationDestinations,
		registered_model.DataSourceRegisteredModel,
		registered_model.DataSourceRegisteredModelVersions,
		serving.DataSourceServingEndpoints,
		sharing.DataSourceShare,
		sharing.DataSourceShares,
		user.DataSourceUsers,
		volume.DataSourceVolumes,
	},
	autoGeneratedDataSources...,
)

type pluginFrameworkOptions struct {
	configCustomizer func(*config.Config) error
}

// PluginFrameworkOption is an interface for acceptance tests to customize the
// plugin framework provider.
type PluginFrameworkOption interface {
	Apply(*pluginFrameworkOptions)
}

type configCustomizer struct {
	configCustomizer func(*config.Config) error
}

func (o *configCustomizer) Apply(options *pluginFrameworkOptions) {
	options.configCustomizer = o.configCustomizer
}

// WithConfigCustomizer allows the caller to customize the SDK config before config resolution,
// so customizer-set fields (e.g. Host) participate in resolveHostMetadata and auth.
func WithConfigCustomizer(customizer func(*config.Config) error) PluginFrameworkOption {
	return &configCustomizer{configCustomizer: customizer}
}
