package tfrcwriter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// VersionsOverrideFilename is the basename of the generated override .tf
// file. The "_override.tf" suffix is what tells terraform to merge it into
// the user's terraform{} block per-attribute rather than treating it as an
// independent block (which would fail with "duplicate terraform block").
//
// The "_tfv2_" prefix is a framework convention namespacing generated files
// (avoids collision with any user-authored *_override.tf file). See
// DESIGN.md §5 ("Override file mechanism — Filename rules").
const VersionsOverrideFilename = "_tfv2_versions_override.tf"

// ProviderSource is the canonical source address for the Databricks
// Terraform provider. It is invariant across versions, including the
// synthetic local build (the local-build pathway also uses
// "databricks/databricks" — only the version string changes to
// providercache.SyntheticVersionLocal).
const ProviderSource = "databricks/databricks"

// versionsOverrideTemplate is the static HCL we write per step.
//
// The version field uses an explicit "=" exact-equality operator so the
// template works for both released and prerelease (local) versions:
//
//   - For released versions like "1.114.0", "= 1.114.0" is unambiguous and
//     wins over any operator the user wrote in their main.tf — including
//     a competing exact pin (Appendix A B-COLLISION).
//   - For the prerelease "99.0.0-local", "=" is the only operator that
//     matches prereleases — ">=", "~>", and "<=" do not (DESIGN.md §8
//     "Synthetic version constraint" + Appendix A test1 / test7).
//
// Per DESIGN.md §5 / Appendix A expA3, terraform's per-attribute override
// merge means the user's other required_providers entries (e.g.
// hashicorp/google) are preserved untouched.
const versionsOverrideTemplate = `# Generated by testframeworkV2. Do not edit.
# This file pins databricks/databricks at the version under test for the
# current step. Per terraform's *_override.tf semantics, only the
# databricks entry's version attribute is overridden; other providers in
# required_providers are preserved from the user's main.tf
# (DESIGN.md §5, Appendix A expA3).

terraform {
  required_providers {
    databricks = {
      source  = "%s"
      version = "= %s"
    }
  }
}
`

// WriteVersionsOverride writes _tfv2_versions_override.tf into workDir,
// pinning databricks/databricks at the given version with exact-equality
// semantics. The version may be a released version ("1.114.0") or the
// synthetic local version ("99.0.0-local") — both work because the
// emitted "= <version>" constraint matches prereleases (DESIGN.md §8).
//
// The file is overwritten if it already exists. Per-step regeneration is
// the expected runner behaviour: each step picks a fresh version and
// rewrites this file before invoking terraform init.
func WriteVersionsOverride(workDir, version string) error {
	if err := requireNonEmpty("workDir", workDir); err != nil {
		return err
	}
	if err := requireNonEmpty("version", version); err != nil {
		return err
	}
	// Guard against version strings that would corrupt the HCL. The runner
	// is the only caller and won't pass adversarial input, but a stray
	// quote, backslash, or newline would produce a baffling "duplicate
	// provider" error at terraform init time. Fail fast with a clear
	// message instead.
	if strings.ContainsAny(version, "\"\\\n\r") {
		return fmt.Errorf("tfrcwriter: version contains invalid characters: %q", version)
	}

	if err := os.MkdirAll(workDir, 0o755); err != nil {
		return fmt.Errorf("tfrcwriter: mkdir %s: %w", workDir, err)
	}

	path := filepath.Join(workDir, VersionsOverrideFilename)
	body := fmt.Sprintf(versionsOverrideTemplate, ProviderSource, version)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return fmt.Errorf("tfrcwriter: write %s: %w", path, err)
	}
	return nil
}
