// Package tfrcwriter generates the per-run .terraformrc CLI config and the
// per-step _tfv2_versions_override.tf override file for testframeworkV2.
//
// See DESIGN.md §5 ("Generated .terraformrc template") for the design
// rationale behind the exact shape of these files. This package is
// deliberately a pure string-templating layer with no terraform-exec
// dependency — that keeps M2 trivially testable and lets the runner (M4)
// compose it with whatever subprocess-spawning strategy it picks.
package tfrcwriter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// TerraformRCFilename is the basename of the generated CLI config file. The
// runner exports TF_CLI_CONFIG_FILE pointing at <workDir>/<TerraformRCFilename>
// for every terraform subprocess in a run.
const TerraformRCFilename = ".terraformrc"

// MirrorIncludePattern is the narrow include glob — see DESIGN.md §5
// ("Why exactly this shape — Narrow include"). Specifically, this is
// intentionally NOT "registry.terraform.io/databricks/*" or "*/*": tester
// confirmed empirically that a wider include breaks user HCL declaring
// hashicorp/google with "provider not found in any of the search locations".
const MirrorIncludePattern = "registry.terraform.io/databricks/databricks"

// terraformRCTemplate is the static HCL we emit per run. The template is
// plain Sprintf interpolation — text/template would be overkill for a file
// this short, and we control all interpolated values (they pass through
// hclString to escape backslashes and double-quotes defensively).
//
// See DESIGN.md §5 for line-by-line rationale of why each block exists:
//
//   - filesystem_mirror with NARROW include — wider patterns break
//     user-authored providers (e.g. hashicorp/google in issue #5672).
//   - direct.exclude mirroring the include — without the explicit direct{}
//     block, terraform falls back to registry-direct for ALL providers,
//     consulting our mirror only as a fallback (wrong direction).
//   - plugin_cache_dir alongside filesystem_mirror — terraform hardlinks
//     resolved provider files instead of re-extracting on each init,
//     which gives us free within-run reuse (F2 in DESIGN.md's binding
//     constraints).
const terraformRCTemplate = `# Generated by testframeworkV2. Do not edit.
# This file is auto-regenerated per run. The framework points
# TF_CLI_CONFIG_FILE at it so terraform ignores ~/.terraformrc entirely
# (DESIGN.md §5 / B1).

provider_installation {
  filesystem_mirror {
    path    = "%s"
    include = ["%s"]
  }

  direct {
    exclude = ["%s"]
  }
}

plugin_cache_dir = "%s"
`

// WriteTerraformRC writes a per-run .terraformrc into workDir and returns
// the absolute path to the generated file. The runner is expected to export
// TF_CLI_CONFIG_FILE=<returned-path> for every terraform subprocess in this
// run, which causes terraform to ignore the user's ~/.terraformrc entirely
// (DESIGN.md §5 / B1).
//
// Parameters:
//
//   - workDir         where to write .terraformrc (created with MkdirAll if
//     missing). Typically "<run-dir>/workdir".
//   - mirrorRoot      absolute path the framework's filesystem_mirror serves
//     from (typically providercache.Cache.Root()). MUST be absolute —
//     terraform resolves relative mirror paths against the subprocess's
//     cwd at runtime, which is fragile (DESIGN.md §5 "Mirror path is
//     absolute").
//   - pluginCacheDir  absolute per-run plugin cache directory (typically
//     "<run-dir>/plugins"). Per-run rather than shared so test isolation
//     is preserved (DESIGN.md §5 "plugin_cache_dir is per-run, not
//     shared"). Note: DESIGN.md §12.6 lists a 2-arg signature
//     WriteTerraformRC(workDir, mirrorRoot) but offers no derivation rule
//     for pluginCacheDir; we make it explicit rather than smuggling a
//     directory convention through workDir.
func WriteTerraformRC(workDir, mirrorRoot, pluginCacheDir string) (string, error) {
	if err := requireNonEmpty("workDir", workDir); err != nil {
		return "", err
	}
	if err := requireNonEmpty("mirrorRoot", mirrorRoot); err != nil {
		return "", err
	}
	if err := requireNonEmpty("pluginCacheDir", pluginCacheDir); err != nil {
		return "", err
	}
	if !filepath.IsAbs(mirrorRoot) {
		return "", fmt.Errorf("tfrcwriter: mirrorRoot must be absolute, got %q", mirrorRoot)
	}
	if !filepath.IsAbs(pluginCacheDir) {
		return "", fmt.Errorf("tfrcwriter: pluginCacheDir must be absolute, got %q", pluginCacheDir)
	}

	if err := os.MkdirAll(workDir, 0o755); err != nil {
		return "", fmt.Errorf("tfrcwriter: mkdir %s: %w", workDir, err)
	}

	path := filepath.Join(workDir, TerraformRCFilename)
	body := fmt.Sprintf(
		terraformRCTemplate,
		hclString(mirrorRoot),
		MirrorIncludePattern,
		MirrorIncludePattern,
		hclString(pluginCacheDir),
	)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("tfrcwriter: write %s: %w", path, err)
	}
	return path, nil
}

// hclString escapes a string for safe inclusion inside HCL "..." quotes. We
// apply the minimal escapes the HCL grammar requires for double-quoted
// strings: backslash and double-quote. This is defense-in-depth — the
// runner controls the values we get and isn't expected to pass adversarial
// input — but the cost is one line and the upside is "if a user's home
// directory contains a backslash on some exotic filesystem, we don't
// silently emit an HCL parse error".
func hclString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}

// requireNonEmpty returns a stable, prefixed error for any empty required
// argument. Centralised so the error wording stays identical across
// helpers — tests depend on the prefix string.
func requireNonEmpty(name, value string) error {
	if value == "" {
		return fmt.Errorf("tfrcwriter: %s is required", name)
	}
	return nil
}
