package tfrcwriter

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestWriteTerraformRC_HappyPath pins the generated.terraformrc against
// every line that calls out as load-bearing. A regression on
// any of these strings would silently break terraform init:
//
// - filesystem_mirror.path (must be absolute, must be the configured
// mirrorRoot — not derived from workDir)
// - filesystem_mirror.include (NARROW; widening breaks user HCL
// declaring other providers "Narrow include")
// - direct.exclude (mirrors the include exactly; otherwise some
// providers route neither through mirror nor direct)
// - plugin_cache_dir (per-run; absolute; enables hardlink reuse — F2)
func TestWriteTerraformRC_HappyPath(t *testing.T) {
	workDir := t.TempDir()
	mirrorRoot := t.TempDir()
	pluginCacheDir := t.TempDir()

	path, err := WriteTerraformRC(workDir, mirrorRoot, pluginCacheDir)
	if err != nil {
		t.Fatalf("WriteTerraformRC: %v", err)
	}
	wantPath := filepath.Join(workDir, TerraformRCFilename)
	if path != wantPath {
		t.Errorf("returned path: got %q want %q", path, wantPath)
	}
	if got := filepath.Base(path); got != ".terraformrc" {
		t.Errorf("filename should be .terraformrc, got %q", got)
	}

	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	got := string(body)

	for _, want := range []string{
		`# Generated by testframeworkV2.`,
		`provider_installation {`,
		`filesystem_mirror {`,
		`path    = "` + mirrorRoot + `"`,
		`include = ["registry.terraform.io/databricks/databricks"]`,
		`direct {`,
		`exclude = ["registry.terraform.io/databricks/databricks"]`,
		`plugin_cache_dir = "` + pluginCacheDir + `"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("body should contain %q\n--- got ---\n%s", want, got)
		}
	}

	// Hard-stop on any of the rejected wider patterns. Catching this in a
	// unit test is far cheaper than reproducing issue #5672's "provider
	// not found in any of the search locations" against a live workspace.
	for _, forbidden := range []string{
		`include = ["registry.terraform.io/*/*"]`,
		`include = ["registry.terraform.io/databricks/*"]`,
		`exclude = ["registry.terraform.io/*/*"]`,
		`exclude = ["registry.terraform.io/databricks/*"]`,
	} {
		if strings.Contains(got, forbidden) {
			t.Errorf("body must not contain forbidden wider pattern %q\n--- got ---\n%s", forbidden, got)
		}
	}
}

// TestWriteTerraformRC_RejectsRelativePaths locks in ("Mirror
// path is absolute"). A relative path silently resolves against the
// subprocess cwd at terraform-run time, breaking mirror lookup. Same
// reasoning for plugin_cache_dir.
func TestWriteTerraformRC_RejectsRelativePaths(t *testing.T) {
	workDir := t.TempDir()
	for _, tc := range []struct {
		name           string
		mirrorRoot     string
		pluginCacheDir string
		wantSub        string
	}{
		{"relative mirror", "rel/mirror", filepath.Join(workDir, "plugins"), "mirrorRoot must be absolute"},
		{"relative cache", filepath.Join(workDir, "mirror"), "rel/cache", "pluginCacheDir must be absolute"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := WriteTerraformRC(workDir, tc.mirrorRoot, tc.pluginCacheDir)
			if err == nil {
				t.Fatal("expected error, got nil")
			}
			if !strings.Contains(err.Error(), tc.wantSub) {
				t.Errorf("error %q does not contain %q", err.Error(), tc.wantSub)
			}
		})
	}
}

// TestWriteTerraformRC_RejectsEmpty ensures the function fails fast on
// missing args rather than emitting a malformed.terraformrc.
func TestWriteTerraformRC_RejectsEmpty(t *testing.T) {
	for _, tc := range []struct {
		name    string
		work    string
		mirror  string
		cache   string
		wantSub string
	}{
		{"empty workDir", "", "/abs/m", "/abs/p", "workDir is required"},
		{"empty mirror", "/abs/w", "", "/abs/p", "mirrorRoot is required"},
		{"empty cache", "/abs/w", "/abs/m", "", "pluginCacheDir is required"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := WriteTerraformRC(tc.work, tc.mirror, tc.cache)
			if err == nil {
				t.Fatal("expected error, got nil")
			}
			if !strings.Contains(err.Error(), tc.wantSub) {
				t.Errorf("error %q does not contain %q", err.Error(), tc.wantSub)
			}
		})
	}
}

// TestWriteTerraformRC_CreatesWorkDir documents that the function bootstraps
// the workDir if it does not yet exist. The runner generally creates run
// directories beforehand, but it is gentle on early callers (e.g. ad-hoc
// tests of this package) and harmless when the dir already exists.
func TestWriteTerraformRC_CreatesWorkDir(t *testing.T) {
	parent := t.TempDir()
	workDir := filepath.Join(parent, "missing", "subdir")
	mirror := t.TempDir()
	cache := t.TempDir()

	path, err := WriteTerraformRC(workDir, mirror, cache)
	if err != nil {
		t.Fatalf("WriteTerraformRC: %v", err)
	}
	if _, err := os.Stat(path); err != nil {
		t.Errorf("file not written: %v", err)
	}
}

// TestWriteTerraformRC_Idempotent ensures repeated calls overwrite cleanly
// without appending or duplicating directives.
func TestWriteTerraformRC_Idempotent(t *testing.T) {
	workDir := t.TempDir()
	mirror := t.TempDir()
	cache := t.TempDir()

	for i := range 3 {
		if _, err := WriteTerraformRC(workDir, mirror, cache); err != nil {
			t.Fatalf("iteration %d: %v", i, err)
		}
	}
	body, err := os.ReadFile(filepath.Join(workDir, TerraformRCFilename))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	got := string(body)
	for _, directive := range []string{"provider_installation", "filesystem_mirror", "plugin_cache_dir"} {
		if c := strings.Count(got, directive); c != 1 {
			t.Errorf("expected exactly 1 %q after %d writes, got %d", directive, 3, c)
		}
	}
}

// TestHCLString_EscapesSpecialChars confirms our defensive HCL escaping
// turns paths containing backslash or double-quote into a syntactically
// valid HCL string. We exercise the package-private helper via the public
// API by feeding such a path through a writeable temp dir.
func TestHCLString_EscapesSpecialChars(t *testing.T) {
	for _, tc := range []struct {
		in   string
		want string
	}{
		{`/plain/path`, `/plain/path`},
		{`/with"quote`, `/with\"quote`},
		{`/with\backslash`, `/with\\backslash`},
		{`both"and\there`, `both\"and\\there`},
	} {
		if got := hclString(tc.in); got != tc.want {
			t.Errorf("hclString(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

// TestWriteVersionsOverride_HappyPath pins the override.tf body against
// and Appendix A expA3 / B-COLLISION evidence: the file MUST
// declare exactly one databricks entry with source = "databricks/
// databricks" and an explicit "= <version>" exact-equality pin.
func TestWriteVersionsOverride_HappyPath(t *testing.T) {
	workDir := t.TempDir()
	if err := WriteVersionsOverride(workDir, "1.114.0"); err != nil {
		t.Fatalf("WriteVersionsOverride: %v", err)
	}
	path := filepath.Join(workDir, VersionsOverrideFilename)
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	got := string(body)
	for _, want := range []string{
		`terraform {`,
		`required_providers {`,
		`databricks = {`,
		`source  = "databricks/databricks"`,
		`version = "= 1.114.0"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("body should contain %q\n--- got ---\n%s", want, got)
		}
	}
}

// TestWriteVersionsOverride_LocalSynthetic confirms the function writes a
// well-formed pin for the synthetic prerelease "99.0.0-local". This is the
// keystone path for issue #5672's step 4.
func TestWriteVersionsOverride_LocalSynthetic(t *testing.T) {
	workDir := t.TempDir()
	if err := WriteVersionsOverride(workDir, "99.0.0-local"); err != nil {
		t.Fatalf("WriteVersionsOverride(local): %v", err)
	}
	body, err := os.ReadFile(filepath.Join(workDir, VersionsOverrideFilename))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !strings.Contains(string(body), `version = "= 99.0.0-local"`) {
		t.Errorf("body missing local synthetic version pin\n--- got ---\n%s", body)
	}
}

// TestVersionsOverrideFilename_Suffix locks in "Filename
// rules": the file MUST end in _override.tf so terraform recognizes it for
// per-attribute merge. A non-override.tf would clash with the user's own
// terraform {} block at parse time ("duplicate terraform block").
func TestVersionsOverrideFilename_Suffix(t *testing.T) {
	if !strings.HasSuffix(VersionsOverrideFilename, "_override.tf") {
		t.Errorf("VersionsOverrideFilename must end in _override.tf, got %q", VersionsOverrideFilename)
	}
	if !strings.HasPrefix(VersionsOverrideFilename, "_tfv2_") {
		t.Errorf("VersionsOverrideFilename should be namespaced with _tfv2_ prefix, got %q", VersionsOverrideFilename)
	}
}

// TestWriteVersionsOverride_RejectsBadInputs ensures the function fails
// fast on missing or malformed inputs rather than emitting HCL that would
// fail at terraform init time with a confusing parser error.
func TestWriteVersionsOverride_RejectsBadInputs(t *testing.T) {
	dir := t.TempDir()
	for _, tc := range []struct {
		name    string
		workDir string
		version string
	}{
		{"empty workDir", "", "1.0.0"},
		{"empty version", dir, ""},
		{"version with newline", dir, "1.0.0\n"},
		{"version with quote", dir, `1.0.0"`},
		{"version with backslash", dir, `1.0.0\\`},
		{"version with carriage return", dir, "1.0.0\r"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			err := WriteVersionsOverride(tc.workDir, tc.version)
			if err == nil {
				t.Fatal("expected error, got nil")
			}
		})
	}
}

// TestWriteVersionsOverride_OverwritesExisting documents that subsequent
// calls replace the previous pin. The runner regenerates this file per
// step, so any append-on-rewrite
// behaviour would corrupt later steps.
func TestWriteVersionsOverride_OverwritesExisting(t *testing.T) {
	workDir := t.TempDir()
	if err := WriteVersionsOverride(workDir, "1.113.0"); err != nil {
		t.Fatalf("first write: %v", err)
	}
	if err := WriteVersionsOverride(workDir, "1.114.0"); err != nil {
		t.Fatalf("second write: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(workDir, VersionsOverrideFilename))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	got := string(body)
	if !strings.Contains(got, `"= 1.114.0"`) {
		t.Errorf("expected 1.114.0 pin after second write, got: %s", got)
	}
	if strings.Contains(got, `"= 1.113.0"`) {
		t.Errorf("expected 1.113.0 to be replaced, got: %s", got)
	}
	if c := strings.Count(got, `version = `); c != 1 {
		t.Errorf("expected exactly 1 version pin, got %d", c)
	}
}

// TestProviderSource_Constant pins the canonical provider source. A bug
// here would produce a never-resolving terraform error.
func TestProviderSource_Constant(t *testing.T) {
	if ProviderSource != "databricks/databricks" {
		t.Errorf("ProviderSource: got %q want %q", ProviderSource, "databricks/databricks")
	}
}

// TestWriteVersionsOverride_CreatesWorkDir mirrors the.terraformrc helper:
// missing workDir is bootstrapped rather than silently failing.
func TestWriteVersionsOverride_CreatesWorkDir(t *testing.T) {
	parent := t.TempDir()
	workDir := filepath.Join(parent, "missing", "subdir")
	if err := WriteVersionsOverride(workDir, "1.114.0"); err != nil {
		t.Fatalf("WriteVersionsOverride: %v", err)
	}
	if _, err := os.Stat(filepath.Join(workDir, VersionsOverrideFilename)); err != nil {
		t.Errorf("file not written: %v", err)
	}
}
