name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup gotestsum
      uses: autero1/action-gotestsum@v0.1.0

    - name: Run Linting Unit tests
      run: |
        # Install 
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
        make test
