name: run tests

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - *
    paths-ignore:
      - docs/*
      - scripts/*
      - *.md

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Download gotestsum and golangci
        run: |
          curl -sSL "https://github.com/gotestyourself/gotestsum/releases/download/v0.4.2/gotestsum_0.4.2_linux_amd64.tar.gz" | sudo tar -xz -C /usr/local/bin gotestsum
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
      - name: Run tests
        run: make test
      - name: Publish coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage.txt